import { ref } from 'vue'

type Language = 'ro' | 'en' | 'de'

type Dictionary = Record<string, { ro: string; en: string }>

const STORAGE_KEY = 'app-language'

const initialLanguage = (): Language => {
  const saved = localStorage.getItem(STORAGE_KEY)
  if (saved === 'ro' || saved === 'en' || saved === 'de') {
    return saved
  }
  return 'ro'
}

const currentLanguage = ref<Language>(initialLanguage())

const dictionary: Dictionary = {
  language: { ro: 'Limbă', en: 'Language' },
  romanian: { ro: 'Română', en: 'Romanian' },
  english: { ro: 'Engleză', en: 'English' },
  german: { ro: 'Germană', en: 'German' },
  map: { ro: 'Hartă', en: 'Map' },
  favorites: { ro: 'Favorite', en: 'Favorites' },
  tickets: { ro: 'Bilete', en: 'Tickets' },
  routes: { ro: 'Trasee', en: 'Routes' },
  date: { ro: 'Data', en: 'Date' },
  schedule: { ro: 'Orar', en: 'Schedule' },
  planning: { ro: 'Planificare', en: 'Planning' },
  loadingRoutes: { ro: 'Se încarcă traseele...', en: 'Loading routes...' },
  retry: { ro: 'Reîncearcă', en: 'Retry' },
  routeStations: { ro: 'Stații pe traseu', en: 'Route stations' },
  loading: { ro: 'Se încarcă...', en: 'Loading...' },
  selectRouteHint: { ro: 'Selectează un traseu pentru a-l vedea pe hartă', en: 'Select a route to see it on the map' },
  searchStationPlaceholder: { ro: 'Caută stație... (ex: Gara)', en: 'Search station... (e.g. Train Station)' },
  realtimeSchedule: { ro: 'Orar în timp real', en: 'Real-time schedule' },
  searchStationScheduleHint: {
    ro: 'Caută o stație pentru a vedea autobuzele care urmează să sosească.',
    en: 'Search a station to see upcoming buses.'
  },
  noUpcomingTripsHour: { ro: 'Nu există curse în următoarea oră.', en: 'No trips in the next hour.' },
  tripPlanningTitle: { ro: 'Planifică o călătorie', en: 'Plan a trip' },
  tripPlanningHint: { ro: 'Caută orice adresă sau stație, alege ora și găsim cel mai bun traseu.', en: 'Search any address or station, choose time, and find the best route.' },
  originPlaceholder: { ro: 'Stație sau adresă de plecare...', en: 'Departure station or address...' },
  destinationPlaceholder: { ro: 'Stație sau adresă destinație...', en: 'Destination station or address...' },
  departure: { ro: 'Plecare', en: 'Departure' },
  destination: { ro: 'Destinație', en: 'Destination' },
  from: { ro: 'din', en: 'from' },
  to: { ro: 'către', en: 'to' },
  selectedResults: { ro: 'rezultate', en: 'results' },
  now: { ro: 'Acum', en: 'Now' },
  inMinutes: { ro: 'în {n} min', en: 'in {n} min' },
  transfer: { ro: 'transfer', en: 'transfer' },
  stations: { ro: 'stații', en: 'stops' },
  transfers: { ro: 'schimbări', en: 'transfers' },
  departureAfter: { ro: 'Plecare după ora', en: 'Depart after' },
  searchTrips: { ro: 'Caută curse', en: 'Search trips' },
  searching: { ro: 'Se caută...', en: 'Searching...' },
  noTripsFound: { ro: 'Nu s-au găsit curse în intervalul selectat.', en: 'No trips found for the selected time range.' },
  tryDifferentTime: { ro: 'Încearcă o altă oră sau locații diferite.', en: 'Try a different time or locations.' },
  geoSearchTitle: { ro: 'Căutare geografică', en: 'Geographic search' },
  geoSearchPlaceholder: { ro: 'Ex: Strada Unirii nr 19', en: 'Ex: 19 Unirii Street' },
  geoSearchButton: { ro: 'Du-mă acolo', en: 'Go there' },
  geoSearchNoResult: { ro: 'Adresa nu a fost găsită.', en: 'Address not found.' },
  loginTitle: { ro: 'Autentificare Tursib', en: 'Tursib Login' },
  loginSubtitle: { ro: 'Conectează-te pentru a accesa favoritele tale', en: 'Sign in to access your favorites' },
  username: { ro: 'Utilizator', en: 'Username' },
  password: { ro: 'Parolă', en: 'Password' },
  showPassword: { ro: 'Arată parola', en: 'Show password' },
  hidePassword: { ro: 'Ascunde parola', en: 'Hide password' },
  rememberMe: { ro: 'Ține-mă minte', en: 'Remember me' },
  connecting: { ro: 'Se conectează...', en: 'Signing in...' },
  loginButton: { ro: 'Autentificare', en: 'Sign in' },
  loginHint: { ro: 'Autentifică-te pentru a salva locațiile favorite', en: 'Sign in to save favorite places' },
  or: { ro: 'SAU', en: 'OR' },
  noAccount: { ro: 'Nu ai cont?', en: "Don't have an account?" },
  createOne: { ro: 'Creează unul', en: 'Create one' },
  backToMap: { ro: 'Înapoi la hartă', en: 'Back to map' },
  wrongCredentials: { ro: 'Username sau parolă incorectă', en: 'Invalid username or password' },
  googleLoginError: { ro: 'Eroare la autentificarea cu Google', en: 'Google sign-in failed' },
  signupTitle: { ro: 'Creare Cont Tursib', en: 'Create Tursib Account' },
  signupSubtitle: { ro: 'Creează un cont pentru a salva favoritele tale', en: 'Create an account to save your favorites' },
  chooseUsername: { ro: 'Alege un username', en: 'Choose a username' },
  choosePassword: { ro: 'Alege o parolă', en: 'Choose a password' },
  enterUsername: { ro: 'Introdu username-ul', en: 'Enter your username' },
  enterPassword: { ro: 'Introdu parola', en: 'Enter your password' },
  confirmPassword: { ro: 'Confirmă parola', en: 'Confirm password' },
  confirmYourPassword: { ro: 'Confirmă parola', en: 'Confirm your password' },
  min3Chars: { ro: 'Minim 3 caractere', en: 'Minimum 3 characters' },
  min6Chars: { ro: 'Minim 6 caractere (recomandăm: litere, cifre, simboluri)', en: 'Minimum 6 characters (recommended: letters, numbers, symbols)' },
  passwordsDoNotMatch: { ro: 'Parolele nu coincid', en: 'Passwords do not match' },
  creatingAccount: { ro: 'Se creează contul...', en: 'Creating account...' },
  createAccount: { ro: 'Creare Cont', en: 'Create account' },
  accountHint: { ro: 'Contul îți permite să salvezi locațiile favorite', en: 'Your account lets you save favorite locations' },
  alreadyHaveAccount: { ro: 'Ai deja cont?', en: 'Already have an account?' },
  loginNow: { ro: 'Autentifică-te', en: 'Sign in' },
  accountCreatedRedirect: { ro: 'Cont creat cu succes! Te redirecționăm...', en: 'Account created successfully! Redirecting...' },
  signupGenericError: { ro: 'Eroare la crearea contului. Username-ul ar putea fi deja folosit.', en: 'Error creating account. Username might already be taken.' },
  veryWeak: { ro: 'Foarte slabă', en: 'Very weak' },
  weak: { ro: 'Slabă', en: 'Weak' },
  medium: { ro: 'Medie', en: 'Medium' },
  good: { ro: 'Bună', en: 'Good' },
  excellent: { ro: 'Excelentă', en: 'Excellent' },
  favLocationsTitle: { ro: 'Locații Favorite', en: 'Favorite Locations' },
  favLocationsSubtitle: { ro: 'Salvează locațiile tale frecvente pentru acces rapid', en: 'Save frequent places for quick access' },
  addHome: { ro: 'Adaugă Casă', en: 'Add Home' },
  addWork: { ro: 'Adaugă Serviciu', en: 'Add Work' },
  homeName: { ro: 'Casă', en: 'Home' },
  workName: { ro: 'Serviciu', en: 'Work' },
  addNewLocation: { ro: 'Locație Nouă', en: 'New Location' },
  noSavedLocations: { ro: 'Nicio locație salvată', en: 'No saved locations' },
  addFrequentLocations: { ro: 'Adaugă locațiile tale frecvente pentru a le accesa rapid', en: 'Add frequent places for quick access' },
  editLocation: { ro: 'Editează Locație', en: 'Edit Location' },
  addLocation: { ro: 'Adaugă Locație', en: 'Add Location' },
  locationName: { ro: 'Nume locație', en: 'Location name' },
  locationAddress: { ro: 'Adresă', en: 'Address' },
  icon: { ro: 'Icon', en: 'Icon' },
  cancel: { ro: 'Anulează', en: 'Cancel' },
  save: { ro: 'Salvează', en: 'Save' },
  add: { ro: 'Adaugă', en: 'Add' },
  deleteLocationConfirm: { ro: 'Ștergi locația "{name}"?', en: 'Delete location "{name}"?' },
  statsMyTitle: { ro: 'Statisticile Mele', en: 'My Statistics' },
  appUsage: { ro: 'Utilizarea aplicației', en: 'App usage' },
  totalSearches: { ro: 'Căutări Total', en: 'Total Searches' },
  totalTrips: { ro: 'Călătorii', en: 'Trips' },
  timeUsed: { ro: 'Timp Folosit', en: 'Time Used' },
  avgPerDay: { ro: 'Medie/Zi', en: 'Avg/Day' },
  last7Days: { ro: 'Activitate Ultimele 7 Zile', en: 'Activity Last 7 Days' },
  searches: { ro: 'căutări', en: 'searches' },
  topRoutes: { ro: 'Trasee Preferate', en: 'Favorite Routes' },
  noRouteUsed: { ro: 'Nu ai folosit încă niciun traseu', en: 'No routes used yet' },
  lineLabel: { ro: 'Linia', en: 'Line' },
  usages: { ro: 'utilizări', en: 'uses' },
  topStations: { ro: 'Stații Preferate', en: 'Favorite Stations' },
  noStationSearched: { ro: 'Nu ai căutat încă nicio stație', en: 'No stations searched yet' },
  stationLabel: { ro: 'Stația', en: 'Station' },
  accesses: { ro: 'accesări', en: 'opens' },
  resetStatistics: { ro: 'Resetează Statisticile', en: 'Reset Statistics' },
  confirmResetStats: { ro: 'Ești sigur că vrei să resetezi toate statisticile? Această acțiune nu poate fi anulată.', en: 'Are you sure you want to reset all statistics? This action cannot be undone.' },
  statsResetDone: { ro: 'Statisticile au fost resetate!', en: 'Statistics have been reset!' },
  today: { ro: 'Azi', en: 'Today' },
  yesterday: { ro: 'Ieri', en: 'Yesterday' },
  stationLoading: { ro: 'Încărcare...', en: 'Loading...' },
  busesNearby: { ro: 'Autobuze în Apropiere', en: 'Nearby Buses' },
  noBusesNextHour: { ro: 'Nu sunt autobuze programate în următoarele 60 de minute', en: 'No buses scheduled in the next 60 minutes' },
  seconds: { ro: 'secunde', en: 'seconds' },
  minutes: { ro: 'minute', en: 'minutes' },
  routesPassing: { ro: 'Trasee care Trec prin Stație', en: 'Routes Passing Through Station' },
  noRoutesAvailable: { ro: 'Nu sunt trasee disponibile', en: 'No routes available' },
  addToFavorites: { ro: 'Adaugă la Favorite', en: 'Add to Favorites' },
  enableNotifications: { ro: 'Activează Notificări', en: 'Enable Notifications' },
  stationNotFound: { ro: 'Stația nu a fost găsită', en: 'Station not found' },
  stationLoadError: { ro: 'Eroare la încărcarea datelor', en: 'Error loading data' },
  outbound: { ro: 'Dus', en: 'Outbound' },
  inbound: { ro: 'Întors', en: 'Inbound' },
  stationAddedFavorite: { ro: 'Stația a fost adăugată la favorite!', en: 'Station added to favorites!' },
  stationNotificationsSoon: { ro: 'Notificările pentru această stație vor fi activate în curând!', en: 'Notifications for this station will be available soon!' },
  lostBusTitle: { ro: 'Autobuzul s-a rătăcit!', en: 'The bus got lost!' },
  pageNotFoundHint: { ro: 'Pagina pe care o cauți nu există sau a fost mutată.', en: 'The page you are looking for does not exist or was moved.' },
  backHome: { ro: 'Înapoi la Prima Pagină', en: 'Back to Home' },
  back: { ro: 'Înapoi', en: 'Back' },
  triedAccessing: { ro: 'Ai încercat să accesezi:', en: 'Maybe you were looking for:' },
  routesLoadError: { ro: 'Nu s-au putut încărca traseele. Verifică dacă API-ul rulează.', en: 'Could not load routes. Check if API is running.' },
  settings: { ro: 'Setări', en: 'Settings' },
  personalizeExperience: { ro: 'Personalizează experiența ta', en: 'Personalize your experience' },
  appearance: { ro: 'Aspect', en: 'Appearance' },
  darkMode: { ro: 'Mod Întunecat', en: 'Dark Mode' },
  darkModeDesc: { ro: 'Schimbă tema aplicației', en: 'Change the app theme' },
  disableDarkMode: { ro: 'Dezactivează modul întunecat', en: 'Disable dark mode' },
  enableDarkMode: { ro: 'Activează modul întunecat', en: 'Enable dark mode' },
  notifications: { ro: 'Notificări', en: 'Notifications' },
  pushNotifications: { ro: 'Notificări Push', en: 'Push Notifications' },
  pushNotificationsDesc: { ro: 'Primește alerte despre autobuze', en: 'Receive bus alerts' },
  switchToLanguage: { ro: 'Schimbă aplicația în {language}', en: 'Switch the app to {language}' },
  switchLanguageAria: { ro: 'Schimbă limba în {language}', en: 'Switch language to {language}' },
  statistics: { ro: 'Statistici', en: 'Statistics' },
  myStatistics: { ro: 'Statisticile Mele', en: 'My Statistics' },
  usageStatisticsDesc: { ro: 'Vezi statisticile de utilizare', en: 'See usage statistics' },
  account: { ro: 'Cont', en: 'Account' },
  authentication: { ro: 'Autentificare', en: 'Authentication' },
  signInAccountDesc: { ro: 'Conectează-te la cont', en: 'Sign in to your account' },
  information: { ro: 'Informații', en: 'Information' },
  version: { ro: 'Versiune', en: 'Version' },
  build: { ro: 'Build', en: 'Build' },
  aboutApp: { ro: 'Despre Aplicație', en: 'About App' },
  aboutAppDesc: { ro: 'Informații și dezvoltatori', en: 'Information and developers' },
  dataAndPrivacy: { ro: 'Date și confidențialitate', en: 'Data & Privacy' },
  sound: { ro: 'Sunet', en: 'Sound' },
  soundDesc: { ro: 'La notificări noi', en: 'On new notifications' },
  vibration: { ro: 'Vibrație', en: 'Vibration' },
  light: { ro: 'Light', en: 'Light' },
  dark: { ro: 'Dark', en: 'Dark' },
  auto: { ro: 'Auto', en: 'Auto' },
  adminTitle: { ro: 'Tursib Admin', en: 'Tursib Admin' },
  adminWelcome: { ro: 'Bine ai venit! Autentifică-te pentru a continua', en: 'Welcome! Sign in to continue' },
  adminUsernamePlaceholder: { ro: 'Introdu username-ul', en: 'Enter username' },
  adminPasswordPlaceholder: { ro: 'Introdu parola', en: 'Enter password' },
  adminAccessRestricted: { ro: 'Accesul este restricționat administratorilor autorizați', en: 'Access is restricted to authorized administrators' },
  adminBackToMap: { ro: 'Înapoi la hartă', en: 'Back to map' },
  adminWrongCredentials: { ro: 'Username sau parolă incorectă', en: 'Invalid username or password' },
  adminPanel: { ro: 'Panou de Administrare', en: 'Administration Panel' },
  adminPanelSubtitle: { ro: 'Gestionați traseele și stațiile de transport public Sibiu', en: 'Manage Sibiu public transport routes and stations' },
  analytics: { ro: 'Analitice', en: 'Analytics' },
  logout: { ro: 'Deconectare', en: 'Logout' },
  manageRoutes: { ro: 'Gestionare Trasee', en: 'Manage Routes' },
  addNewRoute: { ro: 'Adaugă Traseu Nou', en: 'Add New Route' },
  routeNumber: { ro: 'Număr Traseu', en: 'Route Number' },
  name: { ro: 'Nume', en: 'Name' },
  color: { ro: 'Culoare', en: 'Color' },
  actions: { ro: 'Acțiuni', en: 'Actions' },
  edit: { ro: 'Editează', en: 'Edit' },
  changeColor: { ro: 'Schimbă culoare', en: 'Change color' },
  delete: { ro: 'Șterge', en: 'Delete' },
  editRouteTitle: { ro: 'Editează Traseu', en: 'Edit Route' },
  createRouteTitle: { ro: 'Adaugă Traseu Nou', en: 'Add New Route' },
  colorHex: { ro: 'Culoare (hex)', en: 'Color (hex)' },
  create: { ro: 'Creează', en: 'Create' },
  changeColorTitle: { ro: 'Schimbă Culoarea', en: 'Change Color' },
  newColor: { ro: 'Culoare nouă', en: 'New color' },
  confirmDeleteRoute: { ro: 'Sigur vrei să ștergi traseul {route}?', en: 'Are you sure you want to delete route {route}?' },
  routesLoadErrorWithMessage: { ro: 'Eroare la încărcarea traseelor: {message}', en: 'Error loading routes: {message}' },
  routeDeleteError: { ro: 'Eroare la ștergerea traseului', en: 'Error deleting route' },
  routeSaveError: { ro: 'Eroare la salvarea traseului', en: 'Error saving route' },
  routeColorUpdateError: { ro: 'Eroare la actualizarea culorii', en: 'Error updating color' },
  manageStations: { ro: 'Gestionare Stații', en: 'Manage Stations' },
  addNewStation: { ro: 'Adaugă Stație Nouă', en: 'Add New Station' },
  stationName: { ro: 'Nume Stație', en: 'Station Name' },
  latitude: { ro: 'Latitudine', en: 'Latitude' },
  longitude: { ro: 'Longitudine', en: 'Longitude' },
  viewOnMap: { ro: 'Vezi pe hartă', en: 'View on map' },
  editStationTitle: { ro: 'Editează Stație', en: 'Edit Station' },
  createStationTitle: { ro: 'Adaugă Stație Nouă', en: 'Add New Station' },
  stationExample: { ro: 'Ex: Piața Mare', en: 'Ex: Main Square' },
  mapTip: { ro: 'Tip: Click pe hartă pentru a selecta coordonatele automat', en: 'Tip: Click on map to auto-select coordinates' },
  confirmDeleteStation: { ro: 'Sigur vrei să ștergi stația "{name}"?\n\nAtenție: Aceasta poate afecta traseele care folosesc această stație!', en: 'Are you sure you want to delete station "{name}"?\n\nWarning: This can affect routes using this station!' },
  stationsLoadErrorWithMessage: { ro: 'Eroare la încărcarea stațiilor: {message}', en: 'Error loading stations: {message}' },
  stationDeleteError: { ro: 'Eroare la ștergerea stației', en: 'Error deleting station' },
  stationSaveError: { ro: 'Eroare la salvarea stației', en: 'Error saving station' },
  analyticsDashboard: { ro: 'Dashboard Analitice', en: 'Analytics Dashboard' },
  analyticsSubtitle: { ro: 'Statistici în timp real pentru sistemul de transport public', en: 'Real-time statistics for the public transport system' },
  loadingData: { ro: 'Se încarcă datele...', en: 'Loading data...' },
  activeBusesLabel: { ro: 'Autobuze Active', en: 'Active Buses' },
  avgOccupancyLabel: { ro: 'Ocupare Medie', en: 'Average Occupancy' },
  totalRoutesLabel: { ro: 'Trasee Totale', en: 'Total Routes' },
  totalStationsLabel: { ro: 'Stații Totale', en: 'Total Stations' },
  avgOccupancyByRoute: { ro: 'Ocupare Medie pe Traseu', en: 'Average Occupancy by Route' },
  activeBusesRealtime: { ro: 'Autobuze Active în Timp Real', en: 'Real-time Active Buses' },
  occupancyDistribution: { ro: 'Distribuție Nivel Ocupare', en: 'Occupancy Distribution' },
  topStationsTraffic: { ro: 'Top Stații Tranzitate', en: 'Top Transit Stations' },
  liveBuses: { ro: 'Autobuze Live', en: 'Live Buses' },
  live: { ro: 'LIVE', en: 'LIVE' },
  speed: { ro: 'Viteză', en: 'Speed' },
  occupancy: { ro: 'Ocupare', en: 'Occupancy' },
  position: { ro: 'Poziție', en: 'Position' },
  occupancyAvgPercent: { ro: 'Ocupare Medie (%)', en: 'Average Occupancy (%)' },
  occupancyLow: { ro: 'Scăzută (<40%)', en: 'Low (<40%)' },
  occupancyMedium: { ro: 'Medie (40-70%)', en: 'Medium (40-70%)' },
  occupancyHigh: { ro: 'Ridicată (>70%)', en: 'High (>70%)' },
  passCount: { ro: 'Număr treceri', en: 'Pass count' },
  continueWithGoogle: { ro: 'Continuă cu Google', en: 'Continue with Google' },
  fleet: { ro: 'Flotă', en: 'Fleet' },
  users: { ro: 'Utilizatori', en: 'Users' },
  ticketsAndRevenue: { ro: 'Bilete & Venituri', en: 'Tickets & Revenue' },
  close: { ro: 'Închide', en: 'Close' },
  more: { ro: 'Mai mult', en: 'More' },
  tripHistory: { ro: 'Istoric călătorii', en: 'Trip History' },
  viewTutorial: { ro: 'Vezi tutorialul', en: 'View Tutorial' },
  viewTutorialDesc: { ro: 'Revedere ghidul de utilizare al aplicației', en: 'Review the app usage guide' },
  profile: { ro: 'Profilul meu', en: 'My Profile' },
  profileDesc: { ro: 'Statistici și activitate', en: 'Statistics and activity' },
  savedSuccessfully: { ro: 'Salvat cu succes!', en: 'Saved successfully!' },
  deletedSuccessfully: { ro: 'Șters cu succes!', en: 'Deleted successfully!' },
  addedToFavorites: { ro: 'Adăugat la favorite!', en: 'Added to favorites!' },
  confirmDelete: { ro: 'Ești sigur că vrei să ștergi?', en: 'Are you sure you want to delete?' },
  hideSidebar: { ro: 'Ascunde sidebar', en: 'Hide sidebar' },
  showSidebar: { ro: 'Arată sidebar', en: 'Show sidebar' },
  showLimitedBuses: { ro: 'Arată 30 autobuze', en: 'Show 30 buses' },
  showAllBusesLabel: { ro: 'Arată toate autobuzele', en: 'Show all buses' },
  youAreHere: { ro: 'Tu ești aici', en: 'You are here' },
  navigateHere: { ro: 'Navighează aici', en: 'Navigate here' },
  departFromHere: { ro: 'Plecare de aici', en: 'Depart from here' },
  addToFavoritesAction: { ro: 'Adaugă la favorite', en: 'Add to favorites' },
  closePin: { ro: 'Închide pinul', en: 'Close pin' },
  routeStart: { ro: 'Start traseu', en: 'Route start' },
  routeEnd: { ro: 'Final traseu', en: 'Route end' },
  streetPoint: { ro: 'Punct pe stradă', en: 'Point on street' },
  liveBusesCount: { ro: 'autobuze live', en: 'live buses' },
  nearbyStationsCount: { ro: 'stații apropiate', en: 'nearby stations' },
  activeRoute: { ro: 'Traseu activ', en: 'Active route' },
  boarding: { ro: 'Urcare', en: 'Boarding' },
  transferLabel: { ro: 'Transfer', en: 'Transfer' },
  transferLabel2: { ro: 'Transfer 2', en: 'Transfer 2' },
  alighting: { ro: 'Coborâre', en: 'Alighting' },
  closeRoute: { ro: 'Închide traseu', en: 'Close route' },
  atStation: { ro: 'La stație', en: 'At station' },
  approachingStation: { ro: 'Se apropie de stație', en: 'Approaching station' },
  departingStation: { ro: 'Pleacă din stație', en: 'Departing station' },
  inTransit: { ro: 'În tranzit', en: 'In transit' },
  busLine: { ro: 'Linia', en: 'Line' },
  busRoute: { ro: 'Traseu', en: 'Route' },
  returnDirection: { ro: 'Retur', en: 'Return' },
  forwardDirection: { ro: 'Tur', en: 'Outbound' },
  nextStation: { ro: 'Următoarea', en: 'Next' },
  speedLabel: { ro: 'Viteză', en: 'Speed' },
  loadingAddress: { ro: 'Se încarcă...', en: 'Loading...' },
  noRouteToDestination: { ro: 'Nu există niciun autobuz care să ducă la această destinație.\n\nÎncearcă să selectezi o destinație mai apropiată de rețeaua de transport public.', en: 'No bus route available to this destination.\n\nTry selecting a destination closer to the public transport network.' },
  walkDirectly: { ro: 'Distanța este scurtă — mergi direct pe jos.', en: 'The distance is short — walk directly.' },
  departureLabel: { ro: 'Plecare', en: 'Departure' },
  yourLocation: { ro: 'Locația ta', en: 'Your location' },
  theDestination: { ro: 'Destinația', en: 'Destination' },
  loginRequired: { ro: 'Trebuie să te autentifici pentru a adăuga la favorite', en: 'You must sign in to add to favorites' },
  loginRequiredTitle: { ro: 'Autentificare necesară', en: 'Login required' },
  tripHistoryTitle: { ro: 'Istoric călătorii', en: 'Trip History' },
  noTripsFound2: { ro: 'Nu s-au găsit călătorii', en: 'No trips found' },
  noTripsSaved: { ro: 'Nicio călătorie salvată', en: 'No saved trips' },
  geolocationNotSupported: { ro: 'Browserul tău nu suportă geolocation!', en: 'Your browser does not support geolocation!' },
  cannotGetLocation: { ro: 'Nu pot găsi locația', en: 'Cannot find location' },
  findingLocation: { ro: 'Găsesc locația...', en: 'Finding location...' },
  myLocation: { ro: 'Locația mea', en: 'My location' },
  notificationSettings: { ro: 'Setări Notificări', en: 'Notification Settings' },
  notificationHistory: { ro: 'Istoric notificări', en: 'Notification history' },
  addRouteBtn: { ro: 'Adaugă', en: 'Add' },
  addRouteHint: { ro: 'Adaugă trasee pentru notificări prioritare', en: 'Add routes for priority notifications' },
  departureFrom: { ro: 'Plecare din', en: 'Departure from' },
  destinationSearch: { ro: 'Destinație', en: 'Destination' },
  noRoutesFoundTitle: { ro: 'Nu s-au găsit trasee', en: 'No routes found' },
  locationError: { ro: 'Nu s-a putut obține locația. Verifică permisiunile browser-ului.', en: 'Could not get location. Check browser permissions.' },
  geolocationUnsupported: { ro: 'Geolocation nu este suportat de browser-ul tău.', en: 'Geolocation is not supported by your browser.' },
  noNearbyStations: { ro: 'Nu s-au găsit stații apropiate de locațiile selectate', en: 'No nearby stations found for the selected locations' },
  routeSearchError: { ro: 'Eroare la căutarea traseelor. Verifică dacă backend-ul rulează.', en: 'Error searching routes. Check if the backend is running.' },
  notifActiveForStation: { ro: 'Notificări active pe stație pentru Linia {routeId}.', en: 'Notifications active at station for Line {routeId}.' },
  notifActiveAllLines: { ro: 'Notificări active pentru toate liniile din stație.', en: 'Notifications active for all lines at station.' },
  notifTestPermission: { ro: 'Trebuie să accepți notificările pentru a trimite o notificare de test', en: 'You must allow notifications to send a test notification' },
  notifTestError: { ro: 'Eroare la trimiterea notificării de test', en: 'Error sending test notification' },
  notifActivatedFor: { ro: 'Alerte activate pentru {name}. Stația monitorizată: {station} ({distance} m).', en: 'Alerts enabled for {name}. Monitored station: {station} ({distance} m).' },
  notifNoNearbyStation: { ro: 'Nu am putut identifica o stație apropiată pentru această locație.', en: 'Could not identify a nearby station for this location.' },
  notifPermissionError: { ro: 'Notificările nu au putut fi activate. Verifică permisiunile browserului.', en: 'Notifications could not be enabled. Check browser permissions.' },
  notifGenericError: { ro: 'A apărut o eroare la activarea alertelor pentru această locație.', en: 'An error occurred enabling alerts for this location.' },
  accessDenied: { ro: 'Acces interzis. Ai nevoie de rol de administrator.', en: 'Access denied. You need an administrator role.' },
  alternativeRoutes: { ro: 'Rute Alternative', en: 'Alternative Routes' },
  optionAvailable: { ro: 'opțiune disponibilă', en: 'option available' },
  optionsAvailable: { ro: 'opțiuni disponibile', en: 'options available' },
  fastest: { ro: 'Cea mai rapidă', en: 'Fastest' },
  directRoute: { ro: 'Direct', en: 'Direct' },
  withTransfer: { ro: 'Cu transfer', en: 'With transfer' },
  walkOnFoot: { ro: 'Mers pe jos', en: 'Walk' },
  transferAt: { ro: 'Transfer la', en: 'Transfer at' },
  waitApprox: { ro: 'Așteptare ~', en: 'Wait ~' },
  routeSelected: { ro: 'Rută selectată', en: 'Route selected' },
  selectRoute: { ro: 'Selectează ruta', en: 'Select route' },
  noTransfer: { ro: 'Fără transfer', en: 'No transfer' },
  optionSingular: { ro: 'opțiune', en: 'option' },
  optionPlural: { ro: 'opțiuni', en: 'options' },
  saveTime: { ro: 'Salvează timp', en: 'Saves time' },
  completeRoute: { ro: 'Traseu complet', en: 'Complete route' },
  fromLabel: { ro: 'De la', en: 'From' },
  toLabel: { ro: 'Către', en: 'To' },
  stationsLabel: { ro: 'stații', en: 'stations' },
  hideStations: { ro: 'Ascunde stațiile', en: 'Hide stations' },
  showAllStations: { ro: 'Arată toate stațiile', en: 'Show all stations' },
  arrivalLabel: { ro: 'Sosire', en: 'Arrival' },
  totalDuration: { ro: 'Durată totală', en: 'Total duration' },
  walkingDistance: { ro: 'Distanță pe jos', en: 'Walking distance' },
  myTickets: { ro: 'Biletele mele', en: 'My Tickets' },
  noTicketsYet: { ro: 'Nu ai niciun bilet încă', en: 'You have no tickets yet' },
  price: { ro: 'Preț', en: 'Price' },
  ridesIncluded: { ro: 'Călătorii incluse', en: 'Rides included' },
  purchased: { ro: 'Cumpărat', en: 'Purchased' },
  validUntil: { ro: 'Valabil până la', en: 'Valid until' },
  card: { ro: 'Card', en: 'Card' },
  validationCode: { ro: 'Cod validare', en: 'Validation code' },
  buyTicket: { ro: 'Cumpără bilet', en: 'Buy ticket' },
  payWithCardSubtitle: { ro: 'Plătește cu cardul și primești biletul instant', en: 'Pay with card and get your ticket instantly' },
  ticket: { ro: 'Bilet', en: 'Ticket' },
  payment: { ro: 'Plată', en: 'Payment' },
  confirmation: { ro: 'Confirmare', en: 'Confirmation' },
  chooseTicketType: { ro: 'Alege tipul biletului', en: 'Choose ticket type' },
  cardDetails: { ro: 'Date card', en: 'Card details' },
  processing: { ro: 'Se procesează...', en: 'Processing...' },
  pricePaid: { ro: 'Preț plătit', en: 'Price paid' },
  rides: { ro: 'călătorii', en: 'rides' },
  appTagline: { ro: 'Aplicație web pentru urmărirea în timp real a autobuzelor', en: 'Web app for real-time bus tracking' },
  loadingSchedule: { ro: 'Se încarcă orarul...', en: 'Loading schedule...' },
  noServicesNextHour: { ro: 'Nu sunt curse în următoarea oră', en: 'No services in the next hour' },
  when: { ro: 'Când', en: 'When' },
  leaveNow: { ro: 'Pleacă acum', en: 'Leave now' },
  departAt: { ro: 'Plecare la', en: 'Depart at' },
  arriveBy: { ro: 'Sosire până la', en: 'Arrive by' },
  arrivalTime: { ro: 'Ora sosirii', en: 'Arrival time' },
  departureTime: { ro: 'Ora plecării', en: 'Departure time' },
  resultSingular: { ro: 'rezultat', en: 'result' },
  estArrival: { ro: 'Sosire est.', en: 'Est. arrival' },
  walkToStation: { ro: 'Mers pe jos până la stație', en: 'Walk to station' },
  afterAlightingAt: { ro: 'După coborâre la', en: 'After alighting at' },
  walkMore: { ro: 'mergi pe jos', en: 'walk' },
  toDestination: { ro: 'până la destinație', en: 'to destination' },
  transfersPlural: { ro: 'transferuri', en: 'transfers' },
  onNewNotifications: { ro: 'La notificări noi', en: 'On new notifications' },
  dataPrivacy: { ro: 'Date și confidențialitate', en: 'Data & Privacy' },
  enableAlertsForStation: { ro: 'Activează alerte pentru această stație', en: 'Enable alerts for this station' },
  walkingDirections: { ro: 'Indicații pe jos', en: 'Walking directions' },
  distanceLabel: { ro: 'Distanță', en: 'Distance' },
  estimatedTime: { ro: 'Timp estimat', en: 'Estimated time' },
  calculatingRoute: { ro: 'Se calculează ruta...', en: 'Calculating route...' },
  missingCoordinates: { ro: 'Coordonate lipsă', en: 'Missing coordinates' },
  searchStationShort: { ro: 'Caută stație', en: 'Search station' },
  noStationsFound: { ro: 'Nu s-au găsit stații', en: 'No stations found' },
  customizeAlerts: { ro: 'Personalizează alertele pentru călătoriile tale', en: 'Customize alerts for your trips' },
  activeNotifications: { ro: 'Notificări active', en: 'Active notifications' },
  getAlertsWhenBusesApproach: { ro: 'Primește alerte când autobuzele se apropie', en: 'Get alerts when buses approach' },
  whenToNotify: { ro: 'Când să te notificăm', en: 'When to notify' },
  timeUntilArrival: { ro: 'Timp până la sosire', en: 'Time until arrival' },
  alertTypes: { ro: 'Tipuri de alerte', en: 'Alert types' },
  delayAlerts: { ro: 'Alerte întârzieri', en: 'Delay alerts' },
  notifyWhenDelayed: { ro: 'Notifică-mă când un autobuz are întârziere', en: 'Notify me when a bus is delayed' },
  crowdingAlerts: { ro: 'Alerte aglomerație', en: 'Crowding alerts' },
  findOutWhenFull: { ro: 'Află când un autobuz este aglomerat', en: 'Find out when a bus is crowded' },
  favoriteRoutes: { ro: 'Trasee favorite', en: 'Favorite routes' },
  enterRouteNumber: { ro: 'Introdu numărul traseului', en: 'Enter route number' },
  removeRoute: { ro: 'Elimină traseul', en: 'Remove route' },
  noFavoriteRoutes: { ro: 'Niciun traseu favorit', en: 'No favorite routes' },
  addRoutesForPriority: { ro: 'Adaugă trasee pentru notificări prioritare', en: 'Add routes for priority notifications' },
  testNotification: { ro: 'Trimite notificare de test', en: 'Send test notification' },
  clearAll: { ro: 'Șterge tot', en: 'Clear all' },
  noNotificationsYet: { ro: 'Nicio notificare încă', en: 'No notifications yet' },
  routeWithTransfer: { ro: 'Traseu cu transfer', en: 'Route with transfer' },
  changeBus: { ro: 'Schimbă autobuzul', en: 'Change bus' },
  offlineMode: { ro: 'Mod offline', en: 'Offline mode' },
  total: { ro: 'Total', en: 'Total' },
  departureFromColon: { ro: 'Plecare din:', en: 'Departure from:' },
  searchDeparturePlaceholder: { ro: 'Caută adresă sau stație de plecare...', en: 'Search departure address or station...' },
  addresses: { ro: 'Adrese', en: 'Addresses' },
  stationsSection: { ro: 'Stații', en: 'Stations' },
  destinationColon: { ro: 'Destinație:', en: 'Destination:' },
  destinationPlaceholderShort: { ro: 'Destinație...', en: 'Destination...' },
  searchStationEllipsis: { ro: 'Caută stație...', en: 'Search station...' },
  recentSearches: { ro: 'Căutări Recente', en: 'Recent Searches' },
  noResultsFound: { ro: 'Nu s-au găsit rezultate', en: 'No results found' },
  searchRoutesBtn: { ro: 'Caută Rute', en: 'Search Routes' },
  searchInHistory: { ro: 'Caută în istoric...', en: 'Search history...' },
  tripsCount: { ro: 'călătorii', en: 'trips' },
  tryDifferentSearch: { ro: 'Încearcă alt termen de căutare', en: 'Try a different search term' },
  tripsWillAppearHere: { ro: 'Călătoriile tale vor apărea aici', en: 'Your trips will appear here' },
  confirmClearHistory: { ro: 'Sigur vrei să ștergi tot istoricul? Această acțiune nu poate fi anulată.', en: 'Are you sure you want to clear all history? This action cannot be undone.' },
  aboutAppTitle: { ro: 'Despre aplicație', en: 'About the app' },
  aboutAppText1: { ro: 'Tursib Tracker este o aplicație web modernă care îți permite să urmărești autobuzele Tursib din Sibiu în timp real, să planifici călătoriile și să cumperi bilete digital — totul din browser, fără instalare.', en: 'Tursib Tracker is a modern web app that lets you track Tursib buses in Sibiu in real time, plan trips, and buy tickets digitally — all from the browser, no installation needed.' },
  aboutAppText2: { ro: 'Aplicația folosește datele GTFS oficiale ale Tursib pentru a afișa trasee, orare și estimări de sosire actualizate.', en: 'The app uses official Tursib GTFS data to display routes, schedules, and updated arrival estimates.' },
  features: { ro: 'Funcționalități', en: 'Features' },
  featureInteractiveMap: { ro: 'Hartă interactivă', en: 'Interactive map' },
  featureInteractiveMapDesc: { ro: 'Stații și trasee pe OpenStreetMap', en: 'Stations and routes on OpenStreetMap' },
  featureRealtime: { ro: 'Timp real', en: 'Real time' },
  featureRealtimeDesc: { ro: 'ETA și orare actualizate live', en: 'ETA and schedules updated live' },
  featurePlanningDesc: { ro: 'Calculează ruta optimă', en: 'Calculate the optimal route' },
  featureDigitalTickets: { ro: 'Bilete digitale', en: 'Digital tickets' },
  featureDigitalTicketsDesc: { ro: 'Cumpără direct din aplicație', en: 'Buy directly from the app' },
  featureFavoritesDesc: { ro: 'Salvează stațiile preferate', en: 'Save your favorite stations' },
  featureStatisticsDesc: { ro: 'Istoricul călătoriilor tale', en: 'Your trip history' },
  technicalInfo: { ro: 'Informații tehnice', en: 'Technical information' },
  resourcesSection: { ro: 'Resurse', en: 'Resources' },
  officialSite: { ro: 'site oficial', en: 'official website' },
  tursibFares: { ro: 'Tarife Tursib 2025', en: 'Tursib Fares 2025' },
  madeWithLove: { ro: 'Made with ♥ în Sibiu', en: 'Made with ♥ in Sibiu' },
  busFleet: { ro: 'Flotă Autobuze', en: 'Bus Fleet' },
  registeredTab: { ro: 'Înregistrate', en: 'Registered' },
  addBus: { ro: 'Adaugă autobuz', en: 'Add bus' },
  routesServed: { ro: 'Trasee deservite', en: 'Routes served' },
  avgSpeed: { ro: 'Viteză medie', en: 'Average speed' },
  busIdCol: { ro: 'ID Bus', en: 'Bus ID' },
  directionCol: { ro: 'Direcție', en: 'Direction' },
  nextStationCol: { ro: 'Stația următoare', en: 'Next station' },
  statusCol: { ro: 'Status', en: 'Status' },
  statusActive: { ro: 'Activ', en: 'Active' },
  noResult: { ro: 'Niciun rezultat.', en: 'No results.' },
  noActiveBuses: { ro: 'Niciun autobuz activ momentan.', en: 'No active buses at the moment.' },
  busesCountLabel: { ro: 'autobuze', en: 'buses' },
  licensePlate: { ro: 'Nr. înmatriculare', en: 'License plate' },
  internalName: { ro: 'Denumire internă', en: 'Internal name' },
  currentRoute: { ro: 'Traseu curent', en: 'Current route' },
  unassigned: { ro: 'Neasignat', en: 'Unassigned' },
  inServiceStatus: { ro: 'În serviciu', en: 'In service' },
  garageStatus: { ro: 'Garaj', en: 'Garage' },
  noBusesRegistered: { ro: 'Niciun autobuz înregistrat.', en: 'No buses registered.' },
  editBus: { ro: 'Editează autobuz', en: 'Edit bus' },
  addNewBus: { ro: 'Adaugă autobuz nou', en: 'Add new bus' },
  assignedRoute: { ro: 'Traseu asignat', en: 'Assigned route' },
  unassignedGarage: { ro: 'Neasignat (garaj)', en: 'Unassigned (garage)' },
  dataLoadError: { ro: 'Eroare la încărcarea datelor.', en: 'Error loading data.' },
  busSaveError: { ro: 'Eroare la salvarea autobuzului.', en: 'Error saving bus.' },
  busDeleteError: { ro: 'Eroare la ștergerea autobuzului.', en: 'Error deleting bus.' },
  searchByRouteOrId: { ro: 'Caută după traseu sau ID...', en: 'Search by route or ID...' },
  totalTicketsSold: { ro: 'Total bilete vândute', en: 'Total tickets sold' },
  totalRevenueLabel: { ro: 'Revenue total', en: 'Total revenue' },
  activeTicketsLabel: { ro: 'Bilete active', en: 'Active tickets' },
  soldToday: { ro: 'Vândute azi', en: 'Sold today' },
  searchByUser: { ro: 'Caută după utilizator...', en: 'Search by user...' },
  allStatuses: { ro: 'Toate statusurile', en: 'All statuses' },
  statusExpired: { ro: 'Expirat', en: 'Expired' },
  statusUsed: { ro: 'Folosit', en: 'Used' },
  userCol: { ro: 'Utilizator', en: 'User' },
  typeCol: { ro: 'Tip', en: 'Type' },
  purchasedAt: { ro: 'Cumpărat la', en: 'Purchased at' },
  noTicketsFound: { ro: 'Niciun bilet găsit.', en: 'No tickets found.' },
  ticketsLoadError: { ro: 'Eroare la încărcarea biletelor.', en: 'Error loading tickets.' },
  manageUsers: { ro: 'Gestionare Utilizatori', en: 'Manage Users' },
  usersCount: { ro: 'utilizatori', en: 'users' },
  adminsCount: { ro: 'admini', en: 'admins' },
  searchByUsername: { ro: 'Caută după username...', en: 'Search by username...' },
  allRoles: { ro: 'Toate rolurile', en: 'All roles' },
  roleCol: { ro: 'Rol', en: 'Role' },
  registeredAt: { ro: 'Înregistrat', en: 'Registered' },
  demoteToUser: { ro: 'Retrogradează la User', en: 'Demote to User' },
  promoteToAdmin: { ro: 'Promovează la Admin', en: 'Promote to Admin' },
  deleteUserLabel: { ro: 'Șterge utilizator', en: 'Delete user' },
  noUsersFound: { ro: 'Niciun utilizator găsit.', en: 'No users found.' },
  usersLoadError: { ro: 'Eroare la încărcarea utilizatorilor.', en: 'Error loading users.' },
  roleUpdateError: { ro: 'Eroare la actualizarea rolului.', en: 'Error updating role.' },
  userDeleteError: { ro: 'Eroare la ștergerea utilizatorului.', en: 'Error deleting user.' },
  settingsFooter: { ro: 'Tursib Tracker · Aplicație web pentru urmărirea în timp real a autobuzelor · v1.0.0 · made in Sibiu 🇷🇴', en: 'Tursib Tracker · Web app for real-time bus tracking · v1.0.0 · made in Sibiu 🇷🇴' },
  lineNumber: { ro: 'Linia {number}', en: 'Line {number}' },
  routeCol: { ro: 'Traseu', en: 'Route' },
  gtfsData: { ro: 'Date GTFS', en: 'GTFS Data' },
  confirmDeleteBus: { ro: 'Ștergi autobuzul "{name}" ({internal})?', en: 'Delete bus "{name}" ({internal})?' },
  confirmPromoteUser: { ro: 'Promovezi "{name}" la Admin?', en: 'Promote "{name}" to Admin?' },
  confirmDemoteUser: { ro: 'Retrogradezi "{name}" la User?', en: 'Demote "{name}" to User?' },
  confirmDeleteUser: { ro: 'Ștergi definitiv utilizatorul "{name}"? Acțiunea nu poate fi anulată.', en: 'Permanently delete user "{name}"? This action cannot be undone.' }
}

const germanOverrides: Record<string, string> = {
  language: 'Sprache',
  romanian: 'Rumänisch',
  english: 'Englisch',
  german: 'Deutsch',
  map: 'Karte',
  favorites: 'Favoriten',
  tickets: 'Fahrkarten',
  date: 'Datum',
  routes: 'Routen',
  schedule: 'Fahrplan',
  planning: 'Planung',
  settings: 'Einstellungen',
  personalizeExperience: 'Passe deine Erfahrung an',
  appearance: 'Darstellung',
  darkMode: 'Dunkelmodus',
  darkModeDesc: 'Ändere das App-Design',
  disableDarkMode: 'Dunkelmodus deaktivieren',
  enableDarkMode: 'Dunkelmodus aktivieren',
  notifications: 'Benachrichtigungen',
  pushNotifications: 'Push-Benachrichtigungen',
  pushNotificationsDesc: 'Erhalte Bus-Benachrichtigungen',
  switchToLanguage: 'App auf {language} umstellen',
  switchLanguageAria: 'Sprache auf {language} umstellen',
  statistics: 'Statistiken',
  myStatistics: 'Meine Statistiken',
  usageStatisticsDesc: 'Nutzungsstatistiken anzeigen',
  account: 'Konto',
  authentication: 'Anmeldung',
  signInAccountDesc: 'Melde dich bei deinem Konto an',
  information: 'Informationen',
  version: 'Version',
  build: 'Build',
  aboutApp: 'Über die App',
  aboutAppDesc: 'Informationen und Entwickler',
  loading: 'Laden...',
  searching: 'Suche...',
  cancel: 'Abbrechen',
  save: 'Speichern',
  add: 'Hinzufügen',
  create: 'Erstellen',
  edit: 'Bearbeiten',
  delete: 'Löschen',
  actions: 'Aktionen',
  adminWelcome: 'Willkommen! Melde dich an, um fortzufahren',
  adminAccessRestricted: 'Der Zugriff ist auf autorisierte Administratoren beschränkt',
  adminBackToMap: 'Zurück zur Karte',
  adminWrongCredentials: 'Ungültiger Benutzername oder ungültiges Passwort',
  adminPanel: 'Admin-Panel',
  adminPanelSubtitle: 'Verwalte die öffentlichen Verkehrsrouten und Haltestellen in Sibiu',
  analytics: 'Analysen',
  logout: 'Abmelden',
  manageRoutes: 'Routen verwalten',
  addNewRoute: 'Neue Route hinzufügen',
  routeNumber: 'Routennummer',
  name: 'Name',
  color: 'Farbe',
  changeColor: 'Farbe ändern',
  editRouteTitle: 'Route bearbeiten',
  createRouteTitle: 'Neue Route hinzufügen',
  colorHex: 'Farbe (Hex)',
  changeColorTitle: 'Farbe ändern',
  newColor: 'Neue Farbe',
  confirmDeleteRoute: 'Möchtest du die Route {route} wirklich löschen?',
  routesLoadErrorWithMessage: 'Fehler beim Laden der Routen: {message}',
  routeDeleteError: 'Fehler beim Löschen der Route',
  routeSaveError: 'Fehler beim Speichern der Route',
  routeColorUpdateError: 'Fehler beim Aktualisieren der Farbe',
  manageStations: 'Haltestellen verwalten',
  addNewStation: 'Neue Haltestelle hinzufügen',
  stationName: 'Haltestellenname',
  latitude: 'Breitengrad',
  longitude: 'Längengrad',
  viewOnMap: 'Auf der Karte anzeigen',
  editStationTitle: 'Haltestelle bearbeiten',
  createStationTitle: 'Neue Haltestelle hinzufügen',
  stationExample: 'z. B. Hauptplatz',
  mapTip: 'Tipp: Klicke auf die Karte, um Koordinaten automatisch zu setzen',
  confirmDeleteStation: 'Möchtest du die Haltestelle "{name}" wirklich löschen?\n\nAchtung: Das kann Routen beeinflussen, die diese Haltestelle nutzen!',
  stationsLoadErrorWithMessage: 'Fehler beim Laden der Haltestellen: {message}',
  stationDeleteError: 'Fehler beim Löschen der Haltestelle',
  stationSaveError: 'Fehler beim Speichern der Haltestelle',
  analyticsDashboard: 'Analyse-Dashboard',
  analyticsSubtitle: 'Echtzeitstatistiken für das öffentliche Verkehrssystem',
  loadingData: 'Daten werden geladen...',
  activeBusesLabel: 'Aktive Busse',
  avgOccupancyLabel: 'Durchschnittliche Auslastung',
  totalRoutesLabel: 'Gesamte Routen',
  totalStationsLabel: 'Gesamte Haltestellen',
  avgOccupancyByRoute: 'Durchschnittliche Auslastung pro Route',
  activeBusesRealtime: 'Aktive Busse in Echtzeit',
  occupancyDistribution: 'Auslastungsverteilung',
  topStationsTraffic: 'Top-Haltestellen nach Verkehr',
  liveBuses: 'Live-Busse',
  speed: 'Geschwindigkeit',
  occupancy: 'Auslastung',
  position: 'Position',
  occupancyAvgPercent: 'Durchschnittliche Auslastung (%)',
  occupancyLow: 'Niedrig (<40%)',
  occupancyMedium: 'Mittel (40-70%)',
  occupancyHigh: 'Hoch (>70%)',
  passCount: 'Anzahl Durchfahrten',
  close: 'Schließen',
  more: 'Mehr',
  tripHistory: 'Reiseverlauf',
  viewTutorial: 'Tutorial ansehen',
  viewTutorialDesc: 'Nutzungsanleitung der App erneut ansehen',
  profile: 'Mein Profil',
  profileDesc: 'Statistiken und Aktivität',
  savedSuccessfully: 'Erfolgreich gespeichert!',
  deletedSuccessfully: 'Erfolgreich gelöscht!',
  addedToFavorites: 'Zu Favoriten hinzugefügt!',
  confirmDelete: 'Möchten Sie wirklich löschen?',
  ticketsAndRevenue: 'Fahrkarten & Einnahmen',
  fleet: 'Flotte',
  users: 'Benutzer',
  hideSidebar: 'Seitenleiste ausblenden',
  showSidebar: 'Seitenleiste anzeigen',
  showLimitedBuses: '30 Busse anzeigen',
  showAllBusesLabel: 'Alle Busse anzeigen',
  youAreHere: 'Du bist hier',
  navigateHere: 'Hierher navigieren',
  departFromHere: 'Von hier abfahren',
  addToFavoritesAction: 'Zu Favoriten hinzufügen',
  closePin: 'Pin schließen',
  routeStart: 'Routenstart',
  routeEnd: 'Routenende',
  streetPoint: 'Punkt auf der Straße',
  liveBusesCount: 'Live-Busse',
  nearbyStationsCount: 'Haltestellen in der Nähe',
  activeRoute: 'Aktive Route',
  boarding: 'Einstieg',
  transferLabel: 'Umstieg',
  transferLabel2: 'Umstieg 2',
  alighting: 'Ausstieg',
  closeRoute: 'Route schließen',
  atStation: 'An der Haltestelle',
  approachingStation: 'Nähert sich der Haltestelle',
  departingStation: 'Fährt ab',
  inTransit: 'Unterwegs',
  busLine: 'Linie',
  busRoute: 'Route',
  returnDirection: 'Rückfahrt',
  forwardDirection: 'Hinfahrt',
  nextStation: 'Nächste',
  speedLabel: 'Geschwindigkeit',
  loadingAddress: 'Laden...',
  noRouteToDestination: 'Kein Bus fährt zu diesem Ziel.\n\nVersuche ein Ziel näher am öffentlichen Verkehrsnetz zu wählen.',
  walkDirectly: 'Die Entfernung ist kurz — gehe direkt zu Fuß.',
  departureLabel: 'Abfahrt',
  yourLocation: 'Dein Standort',
  theDestination: 'Ziel',
  loginRequired: 'Du musst dich anmelden, um Favoriten hinzuzufügen',
  loginRequiredTitle: 'Anmeldung erforderlich',
  tripHistoryTitle: 'Reiseverlauf',
  noTripsFound2: 'Keine Reisen gefunden',
  noTripsSaved: 'Keine gespeicherten Reisen',
  geolocationNotSupported: 'Dein Browser unterstützt keine Geolocation!',
  cannotGetLocation: 'Standort kann nicht gefunden werden',
  findingLocation: 'Standort wird gesucht...',
  myLocation: 'Mein Standort',
  notificationSettings: 'Benachrichtigungseinstellungen',
  notificationHistory: 'Benachrichtigungsverlauf',
  addRouteBtn: 'Hinzufügen',
  addRouteHint: 'Routen für Prioritätsbenachrichtigungen hinzufügen',
  departureFrom: 'Abfahrt von',
  destinationSearch: 'Ziel',
  noRoutesFoundTitle: 'Keine Routen gefunden',
  locationError: 'Standort konnte nicht ermittelt werden. Überprüfe die Browserberechtigungen.',
  geolocationUnsupported: 'Geolocation wird von deinem Browser nicht unterstützt.',
  noNearbyStations: 'Keine nahegelegenen Haltestellen für die ausgewählten Standorte gefunden',
  routeSearchError: 'Fehler bei der Routensuche. Überprüfe, ob das Backend läuft.',
  notifActiveForStation: 'Benachrichtigungen aktiv für Linie {routeId}.',
  notifActiveAllLines: 'Benachrichtigungen aktiv für alle Linien an der Haltestelle.',
  notifTestPermission: 'Du musst Benachrichtigungen erlauben, um eine Testbenachrichtigung zu senden',
  notifTestError: 'Fehler beim Senden der Testbenachrichtigung',
  notifActivatedFor: 'Benachrichtigungen aktiviert für {name}. Überwachte Haltestelle: {station} ({distance} m).',
  notifNoNearbyStation: 'Keine nahegelegene Haltestelle für diesen Standort gefunden.',
  notifPermissionError: 'Benachrichtigungen konnten nicht aktiviert werden. Überprüfe die Browserberechtigungen.',
  notifGenericError: 'Ein Fehler ist beim Aktivieren der Benachrichtigungen aufgetreten.',
  accessDenied: 'Zugriff verweigert. Du benötigst eine Administratorrolle.',
  alternativeRoutes: 'Alternative Routen',
  optionAvailable: 'Option verfügbar',
  optionsAvailable: 'Optionen verfügbar',
  fastest: 'Schnellste',
  directRoute: 'Direkt',
  withTransfer: 'Mit Umstieg',
  walkOnFoot: 'Zu Fuß',
  transferAt: 'Umstieg bei',
  waitApprox: 'Warten ~',
  routeSelected: 'Route ausgewählt',
  selectRoute: 'Route auswählen',
  noTransfer: 'Ohne Umstieg',
  optionSingular: 'Option',
  optionPlural: 'Optionen',
  saveTime: 'Zeit sparen',
  completeRoute: 'Vollständige Route',
  fromLabel: 'Von',
  toLabel: 'Nach',
  stationsLabel: 'Haltestellen',
  hideStations: 'Haltestellen ausblenden',
  showAllStations: 'Alle Haltestellen anzeigen',
  arrivalLabel: 'Ankunft',
  totalDuration: 'Gesamtdauer',
  walkingDistance: 'Fußweg',
  myTickets: 'Meine Fahrkarten',
  noTicketsYet: 'Du hast noch keine Fahrkarten',
  price: 'Preis',
  ridesIncluded: 'Fahrten inklusive',
  purchased: 'Gekauft',
  validUntil: 'Gültig bis',
  card: 'Karte',
  validationCode: 'Validierungscode',
  buyTicket: 'Fahrkarte kaufen',
  payWithCardSubtitle: 'Mit Karte bezahlen und sofort erhalten',
  ticket: 'Fahrkarte',
  payment: 'Zahlung',
  confirmation: 'Bestätigung',
  chooseTicketType: 'Fahrkartenart wählen',
  cardDetails: 'Kartendaten',
  processing: 'Wird verarbeitet...',
  pricePaid: 'Bezahlter Preis',
  rides: 'Fahrten',
  appTagline: 'Webanwendung zur Echtzeit-Busverfolgung',
  loadingSchedule: 'Fahrplan wird geladen...',
  noServicesNextHour: 'Keine Fahrten in der nächsten Stunde',
  when: 'Wann',
  leaveNow: 'Jetzt abfahren',
  departAt: 'Abfahrt um',
  arriveBy: 'Ankunft bis',
  arrivalTime: 'Ankunftszeit',
  departureTime: 'Abfahrtszeit',
  resultSingular: 'Ergebnis',
  estArrival: 'Ank. ca.',
  walkToStation: 'Zu Fuß zur Haltestelle',
  afterAlightingAt: 'Nach dem Aussteigen bei',
  walkMore: 'zu Fuß',
  toDestination: 'zum Ziel',
  transfersPlural: 'Umstiege',
  onNewNotifications: 'Bei neuen Benachrichtigungen',
  dataPrivacy: 'Daten & Datenschutz',
  enableAlertsForStation: 'Benachrichtigungen für diese Haltestelle aktivieren',
  walkingDirections: 'Fußweg-Anweisungen',
  distanceLabel: 'Entfernung',
  estimatedTime: 'Geschätzte Zeit',
  calculatingRoute: 'Route wird berechnet...',
  missingCoordinates: 'Fehlende Koordinaten',
  searchStationShort: 'Haltestelle suchen',
  noStationsFound: 'Keine Haltestellen gefunden',
  customizeAlerts: 'Passe Benachrichtigungen für deine Fahrten an',
  activeNotifications: 'Aktive Benachrichtigungen',
  getAlertsWhenBusesApproach: 'Erhalte Benachrichtigungen, wenn Busse sich nähern',
  whenToNotify: 'Wann benachrichtigen',
  timeUntilArrival: 'Zeit bis zur Ankunft',
  alertTypes: 'Benachrichtigungstypen',
  delayAlerts: 'Verspätungsbenachrichtigungen',
  notifyWhenDelayed: 'Benachrichtige mich bei Busverspätungen',
  crowdingAlerts: 'Auslastungsbenachrichtigungen',
  findOutWhenFull: 'Erfahre, wenn ein Bus überfüllt ist',
  favoriteRoutes: 'Lieblingsrouten',
  enterRouteNumber: 'Routennummer eingeben',
  removeRoute: 'Route entfernen',
  noFavoriteRoutes: 'Keine Lieblingsrouten',
  addRoutesForPriority: 'Routen für Prioritätsbenachrichtigungen hinzufügen',
  testNotification: 'Testbenachrichtigung senden',
  clearAll: 'Alle löschen',
  noNotificationsYet: 'Noch keine Benachrichtigungen',
  routeWithTransfer: 'Route mit Umstieg',
  changeBus: 'Bus wechseln',
  offlineMode: 'Offline-Modus',
  total: 'Gesamt',
  departureFromColon: 'Abfahrt von:',
  searchDeparturePlaceholder: 'Abfahrtsadresse oder Haltestelle suchen...',
  addresses: 'Adressen',
  stationsSection: 'Haltestellen',
  destinationColon: 'Ziel:',
  destinationPlaceholderShort: 'Ziel...',
  searchStationEllipsis: 'Haltestelle suchen...',
  recentSearches: 'Letzte Suchen',
  noResultsFound: 'Keine Ergebnisse gefunden',
  searchRoutesBtn: 'Routen suchen',
  searchInHistory: 'Im Verlauf suchen...',
  tripsCount: 'Fahrten',
  tryDifferentSearch: 'Versuche einen anderen Suchbegriff',
  tripsWillAppearHere: 'Deine Fahrten werden hier angezeigt',
  confirmClearHistory: 'Möchtest du den gesamten Verlauf löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
  aboutAppTitle: 'Über die Anwendung',
  aboutAppText1: 'Tursib Tracker ist eine moderne Webanwendung, mit der du Tursib-Busse in Sibiu in Echtzeit verfolgen, Fahrten planen und Fahrkarten digital kaufen kannst — alles im Browser, ohne Installation.',
  aboutAppText2: 'Die App nutzt offizielle GTFS-Daten von Tursib, um Routen, Fahrpläne und aktuelle Ankunftsschätzungen anzuzeigen.',
  features: 'Funktionen',
  featureInteractiveMap: 'Interaktive Karte',
  featureInteractiveMapDesc: 'Haltestellen und Routen auf OpenStreetMap',
  featureRealtime: 'Echtzeit',
  featureRealtimeDesc: 'ETA und Fahrpläne live aktualisiert',
  featurePlanningDesc: 'Berechne die optimale Route',
  featureDigitalTickets: 'Digitale Fahrkarten',
  featureDigitalTicketsDesc: 'Direkt in der App kaufen',
  featureFavoritesDesc: 'Speichere deine Lieblingshaltestellen',
  featureStatisticsDesc: 'Dein Reiseverlauf',
  technicalInfo: 'Technische Informationen',
  resourcesSection: 'Ressourcen',
  officialSite: 'Offizielle Website',
  tursibFares: 'Tursib-Tarife 2025',
  madeWithLove: 'Made with ♥ in Sibiu',
  busFleet: 'Busflotte',
  registeredTab: 'Registriert',
  addBus: 'Bus hinzufügen',
  routesServed: 'Bediente Routen',
  avgSpeed: 'Durchschnittsgeschwindigkeit',
  busIdCol: 'Bus-ID',
  directionCol: 'Richtung',
  nextStationCol: 'Nächste Haltestelle',
  statusCol: 'Status',
  statusActive: 'Aktiv',
  noResult: 'Keine Ergebnisse.',
  noActiveBuses: 'Momentan keine aktiven Busse.',
  busesCountLabel: 'Busse',
  licensePlate: 'Kennzeichen',
  internalName: 'Interne Bezeichnung',
  currentRoute: 'Aktuelle Route',
  unassigned: 'Nicht zugewiesen',
  inServiceStatus: 'Im Dienst',
  garageStatus: 'Garage',
  noBusesRegistered: 'Keine Busse registriert.',
  editBus: 'Bus bearbeiten',
  addNewBus: 'Neuen Bus hinzufügen',
  assignedRoute: 'Zugewiesene Route',
  unassignedGarage: 'Nicht zugewiesen (Garage)',
  dataLoadError: 'Fehler beim Laden der Daten.',
  busSaveError: 'Fehler beim Speichern des Busses.',
  busDeleteError: 'Fehler beim Löschen des Busses.',
  searchByRouteOrId: 'Nach Route oder ID suchen...',
  totalTicketsSold: 'Gesamt verkaufte Fahrkarten',
  totalRevenueLabel: 'Gesamtumsatz',
  activeTicketsLabel: 'Aktive Fahrkarten',
  soldToday: 'Heute verkauft',
  searchByUser: 'Nach Benutzer suchen...',
  allStatuses: 'Alle Status',
  statusExpired: 'Abgelaufen',
  statusUsed: 'Benutzt',
  userCol: 'Benutzer',
  typeCol: 'Typ',
  purchasedAt: 'Gekauft am',
  noTicketsFound: 'Keine Fahrkarten gefunden.',
  ticketsLoadError: 'Fehler beim Laden der Fahrkarten.',
  manageUsers: 'Benutzer verwalten',
  usersCount: 'Benutzer',
  adminsCount: 'Admins',
  searchByUsername: 'Nach Benutzername suchen...',
  allRoles: 'Alle Rollen',
  roleCol: 'Rolle',
  registeredAt: 'Registriert',
  demoteToUser: 'Zum Benutzer herabstufen',
  promoteToAdmin: 'Zum Admin befördern',
  deleteUserLabel: 'Benutzer löschen',
  noUsersFound: 'Keine Benutzer gefunden.',
  usersLoadError: 'Fehler beim Laden der Benutzer.',
  roleUpdateError: 'Fehler beim Aktualisieren der Rolle.',
  userDeleteError: 'Fehler beim Löschen des Benutzers.',
  settingsFooter: 'Tursib Tracker · Webanwendung zur Echtzeit-Busverfolgung · v1.0.0 · made in Sibiu 🇷🇴',
  lineNumber: 'Linie {number}',
  routeCol: 'Route',
  gtfsData: 'GTFS-Daten',
  confirmDeleteBus: 'Bus "{name}" ({internal}) löschen?',
  confirmPromoteUser: '"{name}" zum Admin befördern?',
  confirmDemoteUser: '"{name}" zum Benutzer herabstufen?',
  confirmDeleteUser: 'Benutzer "{name}" endgültig löschen? Diese Aktion kann nicht rückgängig gemacht werden.'
}

const setLanguage = (language: Language) => {
  currentLanguage.value = language
  localStorage.setItem(STORAGE_KEY, language)
}

const toggleLanguage = () => {
  if (currentLanguage.value === 'ro') {
    setLanguage('en')
    return
  }
  if (currentLanguage.value === 'en') {
    setLanguage('de')
    return
  }
  setLanguage('ro')
}

const t = (key: string, fallback = key, params?: Record<string, string | number>) => {
  const entry = dictionary[key]
  if (!entry) {
    return fallback
  }
  let value = currentLanguage.value === 'de'
    ? germanOverrides[key] ?? entry.en
    : entry[currentLanguage.value]
  if (params) {
    Object.entries(params).forEach(([paramKey, paramValue]) => {
      value = value.replace(`{${paramKey}}`, String(paramValue))
    })
  }
  return value
}

export const useLanguage = () => ({
  currentLanguage,
  setLanguage,
  toggleLanguage,
  t
})

export type { Language }
