import { ref } from 'vue'

type Language = 'ro' | 'en' | 'de'

type Dictionary = Record<string, { ro: string; en: string }>

const STORAGE_KEY = 'app-language'

const initialLanguage = (): Language => {
  const saved = localStorage.getItem(STORAGE_KEY)
  if (saved === 'ro' || saved === 'en' || saved === 'de') {
    return saved
  }
  return 'ro'
}

const currentLanguage = ref<Language>(initialLanguage())

const dictionary: Dictionary = {
  language: { ro: 'Limba', en: 'Language' },
  romanian: { ro: 'Romana', en: 'Romanian' },
  english: { ro: 'Engleza', en: 'English' },
  german: { ro: 'Germana', en: 'German' },
  map: { ro: 'Harta', en: 'Map' },
  favorites: { ro: 'Favorite', en: 'Favorites' },
  routes: { ro: 'Trasee', en: 'Routes' },
  schedule: { ro: 'Orar', en: 'Schedule' },
  planning: { ro: 'Planificare', en: 'Planning' },
  loadingRoutes: { ro: 'Se incarca traseele...', en: 'Loading routes...' },
  retry: { ro: 'Reincearca', en: 'Retry' },
  routeStations: { ro: 'Statii pe traseu', en: 'Route stations' },
  loading: { ro: 'Se incarca...', en: 'Loading...' },
  selectRouteHint: { ro: 'Selecteaza un traseu pentru a-l vedea pe harta', en: 'Select a route to see it on the map' },
  searchStationPlaceholder: { ro: 'Cauta statie... (ex: Gara)', en: 'Search station... (e.g. Train Station)' },
  realtimeSchedule: { ro: 'Orar in timp real', en: 'Real-time schedule' },
  searchStationScheduleHint: {
    ro: 'Cauta o statie pentru a vedea autobuzele care urmeaza sa soseasca.',
    en: 'Search a station to see upcoming buses.'
  },
  noUpcomingTripsHour: { ro: 'Nu exista curse in urmatoarea ora.', en: 'No trips in the next hour.' },
  tripPlanningTitle: { ro: 'Planifica o calatorie', en: 'Plan a trip' },
  tripPlanningHint: { ro: 'Cauta orice adresa sau statie, alege ora si gasim cel mai bun traseu.', en: 'Search any address or station, choose time, and find the best route.' },
  originPlaceholder: { ro: 'Statie sau adresa de plecare...', en: 'Departure station or address...' },
  destinationPlaceholder: { ro: 'Statie sau adresa destinatie...', en: 'Destination station or address...' },
  departure: { ro: 'Plecare', en: 'Departure' },
  destination: { ro: 'Destinatie', en: 'Destination' },
  from: { ro: 'din', en: 'from' },
  to: { ro: 'catre', en: 'to' },
  selectedResults: { ro: 'rezultate', en: 'results' },
  now: { ro: 'Acum', en: 'Now' },
  inMinutes: { ro: 'in {n} min', en: 'in {n} min' },
  transfer: { ro: 'transfer', en: 'transfer' },
  stations: { ro: 'statii', en: 'stops' },
  transfers: { ro: 'schimbari', en: 'transfers' },
  departureAfter: { ro: 'Plecare dupa ora', en: 'Depart after' },
  searchTrips: { ro: 'Cauta curse', en: 'Search trips' },
  searching: { ro: 'Se cauta...', en: 'Searching...' },
  noTripsFound: { ro: 'Nu s-au gasit curse in intervalul selectat.', en: 'No trips found for the selected time range.' },
  tryDifferentTime: { ro: 'Incearca o alta ora sau locatii diferite.', en: 'Try a different time or locations.' },
  geoSearchTitle: { ro: 'Cautare geografica', en: 'Geographic search' },
  geoSearchPlaceholder: { ro: 'Ex: Strada Unirii nr 19', en: 'Ex: 19 Unirii Street' },
  geoSearchButton: { ro: 'Du-ma acolo', en: 'Go there' },
  geoSearchNoResult: { ro: 'Adresa nu a fost gasita.', en: 'Address not found.' },
  loginTitle: { ro: 'Autentificare Tursib', en: 'Tursib Login' },
  loginSubtitle: { ro: 'Conecteaza-te pentru a accesa favoritele tale', en: 'Sign in to access your favorites' },
  username: { ro: 'Utilizator', en: 'Username' },
  password: { ro: 'Parola', en: 'Password' },
  showPassword: { ro: 'Arata parola', en: 'Show password' },
  hidePassword: { ro: 'Ascunde parola', en: 'Hide password' },
  rememberMe: { ro: 'Tine-ma minte', en: 'Remember me' },
  connecting: { ro: 'Se conecteaza...', en: 'Signing in...' },
  loginButton: { ro: 'Autentificare', en: 'Sign in' },
  loginHint: { ro: 'Autentifica-te pentru a salva locatiile favorite', en: 'Sign in to save favorite places' },
  or: { ro: 'SAU', en: 'OR' },
  noAccount: { ro: 'Nu ai cont?', en: "Don't have an account?" },
  createOne: { ro: 'Creeaza unul', en: 'Create one' },
  backToMap: { ro: 'Inapoi la harta', en: 'Back to map' },
  wrongCredentials: { ro: 'Username sau parola incorecta', en: 'Invalid username or password' },
  googleLoginError: { ro: 'Eroare la autentificarea cu Google', en: 'Google sign-in failed' },
  signupTitle: { ro: 'Creare Cont Tursib', en: 'Create Tursib Account' },
  signupSubtitle: { ro: 'Creeaza un cont pentru a salva favoritele tale', en: 'Create an account to save your favorites' },
  chooseUsername: { ro: 'Alege un username', en: 'Choose a username' },
  choosePassword: { ro: 'Alege o parola', en: 'Choose a password' },
  confirmPassword: { ro: 'Confirma parola', en: 'Confirm password' },
  confirmYourPassword: { ro: 'Confirma parola', en: 'Confirm your password' },
  min3Chars: { ro: 'Minim 3 caractere', en: 'Minimum 3 characters' },
  min6Chars: { ro: 'Minim 6 caractere (recomandam: litere, cifre, simboluri)', en: 'Minimum 6 characters (recommended: letters, numbers, symbols)' },
  passwordsDoNotMatch: { ro: 'Parolele nu coincid', en: 'Passwords do not match' },
  creatingAccount: { ro: 'Se creeaza contul...', en: 'Creating account...' },
  createAccount: { ro: 'Creare Cont', en: 'Create account' },
  accountHint: { ro: 'Contul iti permite sa salvezi locatiile favorite', en: 'Your account lets you save favorite locations' },
  alreadyHaveAccount: { ro: 'Ai deja cont?', en: 'Already have an account?' },
  loginNow: { ro: 'Autentifica-te', en: 'Sign in' },
  accountCreatedRedirect: { ro: 'Cont creat cu succes! Te redirectionam...', en: 'Account created successfully! Redirecting...' },
  signupGenericError: { ro: 'Eroare la crearea contului. Username-ul ar putea fi deja folosit.', en: 'Error creating account. Username might already be taken.' },
  veryWeak: { ro: 'Foarte slaba', en: 'Very weak' },
  weak: { ro: 'Slaba', en: 'Weak' },
  medium: { ro: 'Medie', en: 'Medium' },
  good: { ro: 'Buna', en: 'Good' },
  excellent: { ro: 'Excelenta', en: 'Excellent' },
  favLocationsTitle: { ro: 'Locatii Favorite', en: 'Favorite Locations' },
  favLocationsSubtitle: { ro: 'Salveaza locatiile tale frecvente pentru acces rapid', en: 'Save frequent places for quick access' },
  addHome: { ro: 'Adauga Casa', en: 'Add Home' },
  addWork: { ro: 'Adauga Serviciu', en: 'Add Work' },
  homeName: { ro: 'Casa', en: 'Home' },
  workName: { ro: 'Serviciu', en: 'Work' },
  addNewLocation: { ro: 'Locatie Noua', en: 'New Location' },
  noSavedLocations: { ro: 'Nicio locatie salvata', en: 'No saved locations' },
  addFrequentLocations: { ro: 'Adauga locatiile tale frecvente pentru a le accesa rapid', en: 'Add frequent places for quick access' },
  editLocation: { ro: 'Editeaza Locatie', en: 'Edit Location' },
  addLocation: { ro: 'Adauga Locatie', en: 'Add Location' },
  locationName: { ro: 'Nume locatie', en: 'Location name' },
  locationAddress: { ro: 'Adresa', en: 'Address' },
  icon: { ro: 'Icon', en: 'Icon' },
  cancel: { ro: 'Anuleaza', en: 'Cancel' },
  save: { ro: 'Salveaza', en: 'Save' },
  add: { ro: 'Adauga', en: 'Add' },
  deleteLocationConfirm: { ro: 'Stergi locatia "{name}"?', en: 'Delete location "{name}"?' },
  statsMyTitle: { ro: 'Statisticile Mele', en: 'My Statistics' },
  appUsage: { ro: 'Utilizarea aplicatiei', en: 'App usage' },
  totalSearches: { ro: 'Cautari Total', en: 'Total Searches' },
  totalTrips: { ro: 'Calatorii', en: 'Trips' },
  timeUsed: { ro: 'Timp Folosit', en: 'Time Used' },
  avgPerDay: { ro: 'Medie/Zi', en: 'Avg/Day' },
  last7Days: { ro: 'Activitate Ultimele 7 Zile', en: 'Activity Last 7 Days' },
  searches: { ro: 'cautari', en: 'searches' },
  topRoutes: { ro: 'Trasee Preferate', en: 'Favorite Routes' },
  noRouteUsed: { ro: 'Nu ai folosit inca niciun traseu', en: 'No routes used yet' },
  lineLabel: { ro: 'Linia', en: 'Line' },
  usages: { ro: 'utilizari', en: 'uses' },
  topStations: { ro: 'Statii Preferate', en: 'Favorite Stations' },
  noStationSearched: { ro: 'Nu ai cautat inca nicio statie', en: 'No stations searched yet' },
  stationLabel: { ro: 'Statia', en: 'Station' },
  accesses: { ro: 'accesari', en: 'opens' },
  resetStatistics: { ro: 'Reseteaza Statisticile', en: 'Reset Statistics' },
  confirmResetStats: { ro: 'Esti sigur ca vrei sa resetezi toate statisticile? Aceasta actiune nu poate fi anulata.', en: 'Are you sure you want to reset all statistics? This action cannot be undone.' },
  statsResetDone: { ro: 'Statisticile au fost resetate!', en: 'Statistics have been reset!' },
  today: { ro: 'Azi', en: 'Today' },
  yesterday: { ro: 'Ieri', en: 'Yesterday' },
  stationLoading: { ro: 'Incarcare...', en: 'Loading...' },
  busesNearby: { ro: 'Autobuze in Apropiere', en: 'Nearby Buses' },
  noBusesNextHour: { ro: 'Nu sunt autobuze programate in urmatoarele 60 de minute', en: 'No buses scheduled in the next 60 minutes' },
  seconds: { ro: 'secunde', en: 'seconds' },
  minutes: { ro: 'minute', en: 'minutes' },
  routesPassing: { ro: 'Trasee care Trec prin Statie', en: 'Routes Passing Through Station' },
  noRoutesAvailable: { ro: 'Nu sunt trasee disponibile', en: 'No routes available' },
  addToFavorites: { ro: 'Adauga la Favorite', en: 'Add to Favorites' },
  enableNotifications: { ro: 'Activeaza Notificari', en: 'Enable Notifications' },
  stationNotFound: { ro: 'Statia nu a fost gasita', en: 'Station not found' },
  stationLoadError: { ro: 'Eroare la incarcarea datelor', en: 'Error loading data' },
  outbound: { ro: 'Dus', en: 'Outbound' },
  inbound: { ro: 'Intors', en: 'Inbound' },
  stationAddedFavorite: { ro: 'Statia a fost adaugata la favorite!', en: 'Station added to favorites!' },
  stationNotificationsSoon: { ro: 'Notificarile pentru aceasta statie vor fi activate in curand!', en: 'Notifications for this station will be available soon!' },
  lostBusTitle: { ro: 'Autobuzul s-a ratacit!', en: 'The bus got lost!' },
  pageNotFoundHint: { ro: 'Pagina pe care o cauti nu exista sau a fost mutata.', en: 'The page you are looking for does not exist or was moved.' },
  backHome: { ro: 'Inapoi la Prima Pagina', en: 'Back to Home' },
  back: { ro: 'Inapoi', en: 'Back' },
  triedAccessing: { ro: 'Ai incercat sa accesezi:', en: 'Maybe you were looking for:' },
  routesLoadError: { ro: 'Nu s-au putut incarca traseele. Verifica daca API-ul ruleaza.', en: 'Could not load routes. Check if API is running.' },
  settings: { ro: 'Setari', en: 'Settings' },
  personalizeExperience: { ro: 'Personalizeaza experienta ta', en: 'Personalize your experience' },
  appearance: { ro: 'Aspect', en: 'Appearance' },
  darkMode: { ro: 'Mod Intunecat', en: 'Dark Mode' },
  darkModeDesc: { ro: 'Schimba tema aplicatiei', en: 'Change the app theme' },
  disableDarkMode: { ro: 'Dezactiveaza modul intunecat', en: 'Disable dark mode' },
  enableDarkMode: { ro: 'Activeaza modul intunecat', en: 'Enable dark mode' },
  notifications: { ro: 'Notificari', en: 'Notifications' },
  pushNotifications: { ro: 'Notificari Push', en: 'Push Notifications' },
  pushNotificationsDesc: { ro: 'Primeste alerte despre autobuze', en: 'Receive bus alerts' },
  switchToLanguage: { ro: 'Schimba aplicatia in {language}', en: 'Switch the app to {language}' },
  switchLanguageAria: { ro: 'Schimba limba in {language}', en: 'Switch language to {language}' },
  statistics: { ro: 'Statistici', en: 'Statistics' },
  myStatistics: { ro: 'Statisticile Mele', en: 'My Statistics' },
  usageStatisticsDesc: { ro: 'Vezi statisticile de utilizare', en: 'See usage statistics' },
  account: { ro: 'Cont', en: 'Account' },
  authentication: { ro: 'Autentificare', en: 'Authentication' },
  signInAccountDesc: { ro: 'Conecteaza-te la cont', en: 'Sign in to your account' },
  information: { ro: 'Informatii', en: 'Information' },
  version: { ro: 'Versiune', en: 'Version' },
  build: { ro: 'Build', en: 'Build' },
  aboutApp: { ro: 'Despre Aplicatie', en: 'About App' },
  aboutAppDesc: { ro: 'Informatii si dezvoltatori', en: 'Information and developers' },
  adminTitle: { ro: 'Tursib Admin', en: 'Tursib Admin' },
  adminWelcome: { ro: 'Bine ai venit! Autentifica-te pentru a continua', en: 'Welcome! Sign in to continue' },
  adminUsernamePlaceholder: { ro: 'Introdu username-ul', en: 'Enter username' },
  adminPasswordPlaceholder: { ro: 'Introdu parola', en: 'Enter password' },
  adminAccessRestricted: { ro: 'Accesul este restrictionat administratorilor autorizati', en: 'Access is restricted to authorized administrators' },
  adminBackToMap: { ro: 'Inapoi la harta', en: 'Back to map' },
  adminWrongCredentials: { ro: 'Username sau parola incorecta', en: 'Invalid username or password' },
  adminPanel: { ro: 'Panou de Administrare', en: 'Administration Panel' },
  adminPanelSubtitle: { ro: 'Gestionati traseele si statiile de transport public Sibiu', en: 'Manage Sibiu public transport routes and stations' },
  analytics: { ro: 'Analitice', en: 'Analytics' },
  logout: { ro: 'Deconectare', en: 'Logout' },
  manageRoutes: { ro: 'Gestionare Trasee', en: 'Manage Routes' },
  addNewRoute: { ro: 'Adauga Traseu Nou', en: 'Add New Route' },
  routeNumber: { ro: 'Numar Traseu', en: 'Route Number' },
  name: { ro: 'Nume', en: 'Name' },
  color: { ro: 'Culoare', en: 'Color' },
  actions: { ro: 'Actiuni', en: 'Actions' },
  edit: { ro: 'Editeaza', en: 'Edit' },
  changeColor: { ro: 'Schimba culoare', en: 'Change color' },
  delete: { ro: 'Sterge', en: 'Delete' },
  editRouteTitle: { ro: 'Editeaza Traseu', en: 'Edit Route' },
  createRouteTitle: { ro: 'Adauga Traseu Nou', en: 'Add New Route' },
  colorHex: { ro: 'Culoare (hex)', en: 'Color (hex)' },
  create: { ro: 'Creeaza', en: 'Create' },
  changeColorTitle: { ro: 'Schimba Culoarea', en: 'Change Color' },
  newColor: { ro: 'Culoare noua', en: 'New color' },
  confirmDeleteRoute: { ro: 'Sigur vrei sa stergi traseul {route}?', en: 'Are you sure you want to delete route {route}?' },
  routesLoadErrorWithMessage: { ro: 'Eroare la incarcarea traseelor: {message}', en: 'Error loading routes: {message}' },
  routeDeleteError: { ro: 'Eroare la stergerea traseului', en: 'Error deleting route' },
  routeSaveError: { ro: 'Eroare la salvarea traseului', en: 'Error saving route' },
  routeColorUpdateError: { ro: 'Eroare la actualizarea culorii', en: 'Error updating color' },
  manageStations: { ro: 'Gestionare Statii', en: 'Manage Stations' },
  addNewStation: { ro: 'Adauga Statie Noua', en: 'Add New Station' },
  stationName: { ro: 'Nume Statie', en: 'Station Name' },
  latitude: { ro: 'Latitudine', en: 'Latitude' },
  longitude: { ro: 'Longitudine', en: 'Longitude' },
  viewOnMap: { ro: 'Vezi pe harta', en: 'View on map' },
  editStationTitle: { ro: 'Editeaza Statie', en: 'Edit Station' },
  createStationTitle: { ro: 'Adauga Statie Noua', en: 'Add New Station' },
  stationExample: { ro: 'Ex: Piata Mare', en: 'Ex: Main Square' },
  mapTip: { ro: 'Tip: Click pe harta pentru a selecta coordonatele automat', en: 'Tip: Click on map to auto-select coordinates' },
  confirmDeleteStation: { ro: 'Sigur vrei sa stergi statia "{name}"?\n\nAtentie: Aceasta poate afecta traseele care folosesc aceasta statie!', en: 'Are you sure you want to delete station "{name}"?\n\nWarning: This can affect routes using this station!' },
  stationsLoadErrorWithMessage: { ro: 'Eroare la incarcarea statiilor: {message}', en: 'Error loading stations: {message}' },
  stationDeleteError: { ro: 'Eroare la stergerea statiei', en: 'Error deleting station' },
  stationSaveError: { ro: 'Eroare la salvarea statiei', en: 'Error saving station' },
  analyticsDashboard: { ro: 'Dashboard Analitice', en: 'Analytics Dashboard' },
  analyticsSubtitle: { ro: 'Statistici in timp real pentru sistemul de transport public', en: 'Real-time statistics for the public transport system' },
  loadingData: { ro: 'Se incarca datele...', en: 'Loading data...' },
  activeBusesLabel: { ro: 'Autobuze Active', en: 'Active Buses' },
  avgOccupancyLabel: { ro: 'Ocupare Medie', en: 'Average Occupancy' },
  totalRoutesLabel: { ro: 'Trasee Totale', en: 'Total Routes' },
  totalStationsLabel: { ro: 'Statii Totale', en: 'Total Stations' },
  avgOccupancyByRoute: { ro: 'Ocupare Medie pe Traseu', en: 'Average Occupancy by Route' },
  activeBusesRealtime: { ro: 'Autobuze Active in Timp Real', en: 'Real-time Active Buses' },
  occupancyDistribution: { ro: 'Distributie Nivel Ocupare', en: 'Occupancy Distribution' },
  topStationsTraffic: { ro: 'Top Statii Tranzitate', en: 'Top Transit Stations' },
  liveBuses: { ro: 'Autobuze Live', en: 'Live Buses' },
  live: { ro: 'LIVE', en: 'LIVE' },
  speed: { ro: 'Viteza', en: 'Speed' },
  occupancy: { ro: 'Ocupare', en: 'Occupancy' },
  position: { ro: 'Pozitie', en: 'Position' },
  occupancyAvgPercent: { ro: 'Ocupare Medie (%)', en: 'Average Occupancy (%)' },
  occupancyLow: { ro: 'Scazuta (<40%)', en: 'Low (<40%)' },
  occupancyMedium: { ro: 'Medie (40-70%)', en: 'Medium (40-70%)' },
  occupancyHigh: { ro: 'Ridicata (>70%)', en: 'High (>70%)' },
  passCount: { ro: 'Numar treceri', en: 'Pass count' }
}

const germanOverrides: Record<string, string> = {
  language: 'Sprache',
  romanian: 'Rumanisch',
  english: 'Englisch',
  german: 'Deutsch',
  map: 'Karte',
  favorites: 'Favoriten',
  routes: 'Routen',
  schedule: 'Fahrplan',
  planning: 'Planung',
  settings: 'Einstellungen',
  personalizeExperience: 'Passe deine Erfahrung an',
  appearance: 'Darstellung',
  darkMode: 'Dunkelmodus',
  darkModeDesc: 'Andere das App-Design',
  disableDarkMode: 'Dunkelmodus deaktivieren',
  enableDarkMode: 'Dunkelmodus aktivieren',
  notifications: 'Benachrichtigungen',
  pushNotifications: 'Push-Benachrichtigungen',
  pushNotificationsDesc: 'Erhalte Bus-Benachrichtigungen',
  switchToLanguage: 'App auf {language} umstellen',
  switchLanguageAria: 'Sprache auf {language} umstellen',
  statistics: 'Statistiken',
  myStatistics: 'Meine Statistiken',
  usageStatisticsDesc: 'Nutzungsstatistiken anzeigen',
  account: 'Konto',
  authentication: 'Anmeldung',
  signInAccountDesc: 'Melde dich bei deinem Konto an',
  information: 'Informationen',
  version: 'Version',
  build: 'Build',
  aboutApp: 'Uber die App',
  aboutAppDesc: 'Informationen und Entwickler',
  loading: 'Laden...',
  searching: 'Suche...',
  cancel: 'Abbrechen',
  save: 'Speichern',
  add: 'Hinzufugen',
  create: 'Erstellen',
  edit: 'Bearbeiten',
  delete: 'Loschen',
  actions: 'Aktionen',
  adminWelcome: 'Willkommen! Melde dich an, um fortzufahren',
  adminAccessRestricted: 'Der Zugriff ist auf autorisierte Administratoren beschrankt',
  adminBackToMap: 'Zuruck zur Karte',
  adminWrongCredentials: 'Ungultiger Benutzername oder ungultiges Passwort',
  adminPanel: 'Admin-Panel',
  adminPanelSubtitle: 'Verwalte die offentlichen Verkehrsrouten und Haltestellen in Sibiu',
  analytics: 'Analysen',
  logout: 'Abmelden',
  manageRoutes: 'Routen verwalten',
  addNewRoute: 'Neue Route hinzufugen',
  routeNumber: 'Routennummer',
  name: 'Name',
  color: 'Farbe',
  changeColor: 'Farbe andern',
  editRouteTitle: 'Route bearbeiten',
  createRouteTitle: 'Neue Route hinzufugen',
  colorHex: 'Farbe (Hex)',
  changeColorTitle: 'Farbe andern',
  newColor: 'Neue Farbe',
  confirmDeleteRoute: 'Mochtest du die Route {route} wirklich loschen?',
  routesLoadErrorWithMessage: 'Fehler beim Laden der Routen: {message}',
  routeDeleteError: 'Fehler beim Loschen der Route',
  routeSaveError: 'Fehler beim Speichern der Route',
  routeColorUpdateError: 'Fehler beim Aktualisieren der Farbe',
  manageStations: 'Haltestellen verwalten',
  addNewStation: 'Neue Haltestelle hinzufugen',
  stationName: 'Haltestellenname',
  latitude: 'Breitengrad',
  longitude: 'Langengrad',
  viewOnMap: 'Auf der Karte anzeigen',
  editStationTitle: 'Haltestelle bearbeiten',
  createStationTitle: 'Neue Haltestelle hinzufugen',
  stationExample: 'z. B. Hauptplatz',
  mapTip: 'Tipp: Klicke auf die Karte, um Koordinaten automatisch zu setzen',
  confirmDeleteStation: 'Mochtest du die Haltestelle "{name}" wirklich loschen?\n\nAchtung: Das kann Routen beeinflussen, die diese Haltestelle nutzen!',
  stationsLoadErrorWithMessage: 'Fehler beim Laden der Haltestellen: {message}',
  stationDeleteError: 'Fehler beim Loschen der Haltestelle',
  stationSaveError: 'Fehler beim Speichern der Haltestelle',
  analyticsDashboard: 'Analyse-Dashboard',
  analyticsSubtitle: 'Echtzeitstatistiken fur das offentliche Verkehrssystem',
  loadingData: 'Daten werden geladen...',
  activeBusesLabel: 'Aktive Busse',
  avgOccupancyLabel: 'Durchschnittliche Auslastung',
  totalRoutesLabel: 'Gesamte Routen',
  totalStationsLabel: 'Gesamte Haltestellen',
  avgOccupancyByRoute: 'Durchschnittliche Auslastung pro Route',
  activeBusesRealtime: 'Aktive Busse in Echtzeit',
  occupancyDistribution: 'Auslastungsverteilung',
  topStationsTraffic: 'Top-Haltestellen nach Verkehr',
  liveBuses: 'Live-Busse',
  speed: 'Geschwindigkeit',
  occupancy: 'Auslastung',
  position: 'Position',
  occupancyAvgPercent: 'Durchschnittliche Auslastung (%)',
  occupancyLow: 'Niedrig (<40%)',
  occupancyMedium: 'Mittel (40-70%)',
  occupancyHigh: 'Hoch (>70%)',
  passCount: 'Anzahl Durchfahrten'
}

const setLanguage = (language: Language) => {
  currentLanguage.value = language
  localStorage.setItem(STORAGE_KEY, language)
}

const toggleLanguage = () => {
  if (currentLanguage.value === 'ro') {
    setLanguage('en')
    return
  }
  if (currentLanguage.value === 'en') {
    setLanguage('de')
    return
  }
  setLanguage('ro')
}

const t = (key: string, fallback = key, params?: Record<string, string | number>) => {
  const entry = dictionary[key]
  if (!entry) {
    return fallback
  }
  let value = currentLanguage.value === 'de'
    ? germanOverrides[key] ?? entry.en
    : entry[currentLanguage.value]
  if (params) {
    Object.entries(params).forEach(([paramKey, paramValue]) => {
      value = value.replace(`{${paramKey}}`, String(paramValue))
    })
  }
  return value
}

export const useLanguage = () => ({
  currentLanguage,
  setLanguage,
  toggleLanguage,
  t
})

export type { Language }
