import { ref } from 'vue'

type Language = 'ro' | 'en' | 'de'

type Dictionary = Record<string, { ro: string; en: string }>

const STORAGE_KEY = 'app-language'

const initialLanguage = (): Language => {
  const saved = localStorage.getItem(STORAGE_KEY)
  if (saved === 'ro' || saved === 'en' || saved === 'de') {
    return saved
  }
  return 'ro'
}

const currentLanguage = ref<Language>(initialLanguage())

const dictionary: Dictionary = {
  language: { ro: 'Limbă', en: 'Language' },
  romanian: { ro: 'Română', en: 'Romanian' },
  english: { ro: 'Engleză', en: 'English' },
  german: { ro: 'Germană', en: 'German' },
  map: { ro: 'Hartă', en: 'Map' },
  favorites: { ro: 'Favorite', en: 'Favorites' },
  tickets: { ro: 'Bilete', en: 'Tickets' },
  routes: { ro: 'Trasee', en: 'Routes' },
  date: { ro: 'Data', en: 'Date' },
  schedule: { ro: 'Orar', en: 'Schedule' },
  planning: { ro: 'Planificare', en: 'Planning' },
  loadingRoutes: { ro: 'Se încarcă traseele...', en: 'Loading routes...' },
  retry: { ro: 'Reîncearcă', en: 'Retry' },
  routeStations: { ro: 'Stații pe traseu', en: 'Route stations' },
  loading: { ro: 'Se încarcă...', en: 'Loading...' },
  selectRouteHint: { ro: 'Selectează un traseu pentru a-l vedea pe hartă', en: 'Select a route to see it on the map' },
  searchStationPlaceholder: { ro: 'Caută stație... (ex: Gara)', en: 'Search station... (e.g. Train Station)' },
  realtimeSchedule: { ro: 'Orar în timp real', en: 'Real-time schedule' },
  searchStationScheduleHint: {
    ro: 'Caută o stație pentru a vedea autobuzele care urmează să sosească.',
    en: 'Search a station to see upcoming buses.'
  },
  noUpcomingTripsHour: { ro: 'Nu există curse în următoarea oră.', en: 'No trips in the next hour.' },
  tripPlanningTitle: { ro: 'Planifică o călătorie', en: 'Plan a trip' },
  tripPlanningHint: { ro: 'Caută orice adresă sau stație, alege ora și găsim cel mai bun traseu.', en: 'Search any address or station, choose time, and find the best route.' },
  originPlaceholder: { ro: 'Stație sau adresă de plecare...', en: 'Departure station or address...' },
  destinationPlaceholder: { ro: 'Stație sau adresă destinație...', en: 'Destination station or address...' },
  departure: { ro: 'Plecare', en: 'Departure' },
  destination: { ro: 'Destinație', en: 'Destination' },
  from: { ro: 'din', en: 'from' },
  to: { ro: 'către', en: 'to' },
  selectedResults: { ro: 'rezultate', en: 'results' },
  now: { ro: 'Acum', en: 'Now' },
  inMinutes: { ro: 'în {n} min', en: 'in {n} min' },
  transfer: { ro: 'transfer', en: 'transfer' },
  stations: { ro: 'stații', en: 'stops' },
  transfers: { ro: 'schimbări', en: 'transfers' },
  departureAfter: { ro: 'Plecare după ora', en: 'Depart after' },
  searchTrips: { ro: 'Caută curse', en: 'Search trips' },
  searching: { ro: 'Se caută...', en: 'Searching...' },
  noTripsFound: { ro: 'Nu s-au găsit curse în intervalul selectat.', en: 'No trips found for the selected time range.' },
  tryDifferentTime: { ro: 'Încearcă o altă oră sau locații diferite.', en: 'Try a different time or locations.' },
  geoSearchTitle: { ro: 'Căutare geografică', en: 'Geographic search' },
  geoSearchPlaceholder: { ro: 'Ex: Strada Unirii nr 19', en: 'Ex: 19 Unirii Street' },
  geoSearchButton: { ro: 'Du-mă acolo', en: 'Go there' },
  geoSearchNoResult: { ro: 'Adresa nu a fost găsită.', en: 'Address not found.' },
  loginTitle: { ro: 'Autentificare Tursib', en: 'Tursib Login' },
  loginSubtitle: { ro: 'Conectează-te pentru a accesa favoritele tale', en: 'Sign in to access your favorites' },
  username: { ro: 'Utilizator', en: 'Username' },
  password: { ro: 'Parolă', en: 'Password' },
  showPassword: { ro: 'Arată parola', en: 'Show password' },
  hidePassword: { ro: 'Ascunde parola', en: 'Hide password' },
  rememberMe: { ro: 'Ține-mă minte', en: 'Remember me' },
  connecting: { ro: 'Se conectează...', en: 'Signing in...' },
  loginButton: { ro: 'Autentificare', en: 'Sign in' },
  loginHint: { ro: 'Autentifică-te pentru a salva locațiile favorite', en: 'Sign in to save favorite places' },
  or: { ro: 'SAU', en: 'OR' },
  noAccount: { ro: 'Nu ai cont?', en: "Don't have an account?" },
  createOne: { ro: 'Creează unul', en: 'Create one' },
  backToMap: { ro: 'Înapoi la hartă', en: 'Back to map' },
  wrongCredentials: { ro: 'Username sau parolă incorectă', en: 'Invalid username or password' },
  googleLoginError: { ro: 'Eroare la autentificarea cu Google', en: 'Google sign-in failed' },
  signupTitle: { ro: 'Creare Cont Tursib', en: 'Create Tursib Account' },
  signupSubtitle: { ro: 'Creează un cont pentru a salva favoritele tale', en: 'Create an account to save your favorites' },
  chooseUsername: { ro: 'Alege un username', en: 'Choose a username' },
  choosePassword: { ro: 'Alege o parolă', en: 'Choose a password' },
  confirmPassword: { ro: 'Confirmă parola', en: 'Confirm password' },
  confirmYourPassword: { ro: 'Confirmă parola', en: 'Confirm your password' },
  min3Chars: { ro: 'Minim 3 caractere', en: 'Minimum 3 characters' },
  min6Chars: { ro: 'Minim 6 caractere (recomandăm: litere, cifre, simboluri)', en: 'Minimum 6 characters (recommended: letters, numbers, symbols)' },
  passwordsDoNotMatch: { ro: 'Parolele nu coincid', en: 'Passwords do not match' },
  creatingAccount: { ro: 'Se creează contul...', en: 'Creating account...' },
  createAccount: { ro: 'Creare Cont', en: 'Create account' },
  accountHint: { ro: 'Contul îți permite să salvezi locațiile favorite', en: 'Your account lets you save favorite locations' },
  alreadyHaveAccount: { ro: 'Ai deja cont?', en: 'Already have an account?' },
  loginNow: { ro: 'Autentifică-te', en: 'Sign in' },
  accountCreatedRedirect: { ro: 'Cont creat cu succes! Te redirecționăm...', en: 'Account created successfully! Redirecting...' },
  signupGenericError: { ro: 'Eroare la crearea contului. Username-ul ar putea fi deja folosit.', en: 'Error creating account. Username might already be taken.' },
  veryWeak: { ro: 'Foarte slabă', en: 'Very weak' },
  weak: { ro: 'Slabă', en: 'Weak' },
  medium: { ro: 'Medie', en: 'Medium' },
  good: { ro: 'Bună', en: 'Good' },
  excellent: { ro: 'Excelentă', en: 'Excellent' },
  favLocationsTitle: { ro: 'Locații Favorite', en: 'Favorite Locations' },
  favLocationsSubtitle: { ro: 'Salvează locațiile tale frecvente pentru acces rapid', en: 'Save frequent places for quick access' },
  addHome: { ro: 'Adaugă Casă', en: 'Add Home' },
  addWork: { ro: 'Adaugă Serviciu', en: 'Add Work' },
  homeName: { ro: 'Casă', en: 'Home' },
  workName: { ro: 'Serviciu', en: 'Work' },
  addNewLocation: { ro: 'Locație Nouă', en: 'New Location' },
  noSavedLocations: { ro: 'Nicio locație salvată', en: 'No saved locations' },
  addFrequentLocations: { ro: 'Adaugă locațiile tale frecvente pentru a le accesa rapid', en: 'Add frequent places for quick access' },
  editLocation: { ro: 'Editează Locație', en: 'Edit Location' },
  addLocation: { ro: 'Adaugă Locație', en: 'Add Location' },
  locationName: { ro: 'Nume locație', en: 'Location name' },
  locationAddress: { ro: 'Adresă', en: 'Address' },
  icon: { ro: 'Icon', en: 'Icon' },
  cancel: { ro: 'Anulează', en: 'Cancel' },
  save: { ro: 'Salvează', en: 'Save' },
  add: { ro: 'Adaugă', en: 'Add' },
  deleteLocationConfirm: { ro: 'Ștergi locația "{name}"?', en: 'Delete location "{name}"?' },
  statsMyTitle: { ro: 'Statisticile Mele', en: 'My Statistics' },
  appUsage: { ro: 'Utilizarea aplicației', en: 'App usage' },
  totalSearches: { ro: 'Căutări Total', en: 'Total Searches' },
  totalTrips: { ro: 'Călătorii', en: 'Trips' },
  timeUsed: { ro: 'Timp Folosit', en: 'Time Used' },
  avgPerDay: { ro: 'Medie/Zi', en: 'Avg/Day' },
  last7Days: { ro: 'Activitate Ultimele 7 Zile', en: 'Activity Last 7 Days' },
  searches: { ro: 'căutări', en: 'searches' },
  topRoutes: { ro: 'Trasee Preferate', en: 'Favorite Routes' },
  noRouteUsed: { ro: 'Nu ai folosit încă niciun traseu', en: 'No routes used yet' },
  lineLabel: { ro: 'Linia', en: 'Line' },
  usages: { ro: 'utilizări', en: 'uses' },
  topStations: { ro: 'Stații Preferate', en: 'Favorite Stations' },
  noStationSearched: { ro: 'Nu ai căutat încă nicio stație', en: 'No stations searched yet' },
  stationLabel: { ro: 'Stația', en: 'Station' },
  accesses: { ro: 'accesări', en: 'opens' },
  resetStatistics: { ro: 'Resetează Statisticile', en: 'Reset Statistics' },
  confirmResetStats: { ro: 'Ești sigur că vrei să resetezi toate statisticile? Această acțiune nu poate fi anulată.', en: 'Are you sure you want to reset all statistics? This action cannot be undone.' },
  statsResetDone: { ro: 'Statisticile au fost resetate!', en: 'Statistics have been reset!' },
  today: { ro: 'Azi', en: 'Today' },
  yesterday: { ro: 'Ieri', en: 'Yesterday' },
  stationLoading: { ro: 'Încărcare...', en: 'Loading...' },
  busesNearby: { ro: 'Autobuze în Apropiere', en: 'Nearby Buses' },
  noBusesNextHour: { ro: 'Nu sunt autobuze programate în următoarele 60 de minute', en: 'No buses scheduled in the next 60 minutes' },
  seconds: { ro: 'secunde', en: 'seconds' },
  minutes: { ro: 'minute', en: 'minutes' },
  routesPassing: { ro: 'Trasee care Trec prin Stație', en: 'Routes Passing Through Station' },
  noRoutesAvailable: { ro: 'Nu sunt trasee disponibile', en: 'No routes available' },
  addToFavorites: { ro: 'Adaugă la Favorite', en: 'Add to Favorites' },
  enableNotifications: { ro: 'Activează Notificări', en: 'Enable Notifications' },
  stationNotFound: { ro: 'Stația nu a fost găsită', en: 'Station not found' },
  stationLoadError: { ro: 'Eroare la încărcarea datelor', en: 'Error loading data' },
  outbound: { ro: 'Dus', en: 'Outbound' },
  inbound: { ro: 'Întors', en: 'Inbound' },
  stationAddedFavorite: { ro: 'Stația a fost adăugată la favorite!', en: 'Station added to favorites!' },
  stationNotificationsSoon: { ro: 'Notificările pentru această stație vor fi activate în curând!', en: 'Notifications for this station will be available soon!' },
  lostBusTitle: { ro: 'Autobuzul s-a rătăcit!', en: 'The bus got lost!' },
  pageNotFoundHint: { ro: 'Pagina pe care o cauți nu există sau a fost mutată.', en: 'The page you are looking for does not exist or was moved.' },
  backHome: { ro: 'Înapoi la Prima Pagină', en: 'Back to Home' },
  back: { ro: 'Înapoi', en: 'Back' },
  triedAccessing: { ro: 'Ai încercat să accesezi:', en: 'Maybe you were looking for:' },
  routesLoadError: { ro: 'Nu s-au putut încărca traseele. Verifică dacă API-ul rulează.', en: 'Could not load routes. Check if API is running.' },
  settings: { ro: 'Setări', en: 'Settings' },
  personalizeExperience: { ro: 'Personalizează experiența ta', en: 'Personalize your experience' },
  appearance: { ro: 'Aspect', en: 'Appearance' },
  darkMode: { ro: 'Mod Întunecat', en: 'Dark Mode' },
  darkModeDesc: { ro: 'Schimbă tema aplicației', en: 'Change the app theme' },
  disableDarkMode: { ro: 'Dezactivează modul întunecat', en: 'Disable dark mode' },
  enableDarkMode: { ro: 'Activează modul întunecat', en: 'Enable dark mode' },
  notifications: { ro: 'Notificări', en: 'Notifications' },
  pushNotifications: { ro: 'Notificări Push', en: 'Push Notifications' },
  pushNotificationsDesc: { ro: 'Primește alerte despre autobuze', en: 'Receive bus alerts' },
  switchToLanguage: { ro: 'Schimbă aplicația în {language}', en: 'Switch the app to {language}' },
  switchLanguageAria: { ro: 'Schimbă limba în {language}', en: 'Switch language to {language}' },
  statistics: { ro: 'Statistici', en: 'Statistics' },
  myStatistics: { ro: 'Statisticile Mele', en: 'My Statistics' },
  usageStatisticsDesc: { ro: 'Vezi statisticile de utilizare', en: 'See usage statistics' },
  account: { ro: 'Cont', en: 'Account' },
  authentication: { ro: 'Autentificare', en: 'Authentication' },
  signInAccountDesc: { ro: 'Conectează-te la cont', en: 'Sign in to your account' },
  information: { ro: 'Informații', en: 'Information' },
  version: { ro: 'Versiune', en: 'Version' },
  build: { ro: 'Build', en: 'Build' },
  aboutApp: { ro: 'Despre Aplicație', en: 'About App' },
  aboutAppDesc: { ro: 'Informații și dezvoltatori', en: 'Information and developers' },
  dataAndPrivacy: { ro: 'Date și confidențialitate', en: 'Data & Privacy' },
  sound: { ro: 'Sunet', en: 'Sound' },
  soundDesc: { ro: 'La notificări noi', en: 'On new notifications' },
  vibration: { ro: 'Vibrație', en: 'Vibration' },
  light: { ro: 'Light', en: 'Light' },
  dark: { ro: 'Dark', en: 'Dark' },
  auto: { ro: 'Auto', en: 'Auto' },
  adminTitle: { ro: 'Tursib Admin', en: 'Tursib Admin' },
  adminWelcome: { ro: 'Bine ai venit! Autentifică-te pentru a continua', en: 'Welcome! Sign in to continue' },
  adminUsernamePlaceholder: { ro: 'Introdu username-ul', en: 'Enter username' },
  adminPasswordPlaceholder: { ro: 'Introdu parola', en: 'Enter password' },
  adminAccessRestricted: { ro: 'Accesul este restricționat administratorilor autorizați', en: 'Access is restricted to authorized administrators' },
  adminBackToMap: { ro: 'Înapoi la hartă', en: 'Back to map' },
  adminWrongCredentials: { ro: 'Username sau parolă incorectă', en: 'Invalid username or password' },
  adminPanel: { ro: 'Panou de Administrare', en: 'Administration Panel' },
  adminPanelSubtitle: { ro: 'Gestionați traseele și stațiile de transport public Sibiu', en: 'Manage Sibiu public transport routes and stations' },
  analytics: { ro: 'Analitice', en: 'Analytics' },
  logout: { ro: 'Deconectare', en: 'Logout' },
  manageRoutes: { ro: 'Gestionare Trasee', en: 'Manage Routes' },
  addNewRoute: { ro: 'Adaugă Traseu Nou', en: 'Add New Route' },
  routeNumber: { ro: 'Număr Traseu', en: 'Route Number' },
  name: { ro: 'Nume', en: 'Name' },
  color: { ro: 'Culoare', en: 'Color' },
  actions: { ro: 'Acțiuni', en: 'Actions' },
  edit: { ro: 'Editează', en: 'Edit' },
  changeColor: { ro: 'Schimbă culoare', en: 'Change color' },
  delete: { ro: 'Șterge', en: 'Delete' },
  editRouteTitle: { ro: 'Editează Traseu', en: 'Edit Route' },
  createRouteTitle: { ro: 'Adaugă Traseu Nou', en: 'Add New Route' },
  colorHex: { ro: 'Culoare (hex)', en: 'Color (hex)' },
  create: { ro: 'Creează', en: 'Create' },
  changeColorTitle: { ro: 'Schimbă Culoarea', en: 'Change Color' },
  newColor: { ro: 'Culoare nouă', en: 'New color' },
  confirmDeleteRoute: { ro: 'Sigur vrei să ștergi traseul {route}?', en: 'Are you sure you want to delete route {route}?' },
  routesLoadErrorWithMessage: { ro: 'Eroare la încărcarea traseelor: {message}', en: 'Error loading routes: {message}' },
  routeDeleteError: { ro: 'Eroare la ștergerea traseului', en: 'Error deleting route' },
  routeSaveError: { ro: 'Eroare la salvarea traseului', en: 'Error saving route' },
  routeColorUpdateError: { ro: 'Eroare la actualizarea culorii', en: 'Error updating color' },
  manageStations: { ro: 'Gestionare Stații', en: 'Manage Stations' },
  addNewStation: { ro: 'Adaugă Stație Nouă', en: 'Add New Station' },
  stationName: { ro: 'Nume Stație', en: 'Station Name' },
  latitude: { ro: 'Latitudine', en: 'Latitude' },
  longitude: { ro: 'Longitudine', en: 'Longitude' },
  viewOnMap: { ro: 'Vezi pe hartă', en: 'View on map' },
  editStationTitle: { ro: 'Editează Stație', en: 'Edit Station' },
  createStationTitle: { ro: 'Adaugă Stație Nouă', en: 'Add New Station' },
  stationExample: { ro: 'Ex: Piața Mare', en: 'Ex: Main Square' },
  mapTip: { ro: 'Tip: Click pe hartă pentru a selecta coordonatele automat', en: 'Tip: Click on map to auto-select coordinates' },
  confirmDeleteStation: { ro: 'Sigur vrei să ștergi stația "{name}"?\n\nAtenție: Aceasta poate afecta traseele care folosesc această stație!', en: 'Are you sure you want to delete station "{name}"?\n\nWarning: This can affect routes using this station!' },
  stationsLoadErrorWithMessage: { ro: 'Eroare la încărcarea stațiilor: {message}', en: 'Error loading stations: {message}' },
  stationDeleteError: { ro: 'Eroare la ștergerea stației', en: 'Error deleting station' },
  stationSaveError: { ro: 'Eroare la salvarea stației', en: 'Error saving station' },
  analyticsDashboard: { ro: 'Dashboard Analitice', en: 'Analytics Dashboard' },
  analyticsSubtitle: { ro: 'Statistici în timp real pentru sistemul de transport public', en: 'Real-time statistics for the public transport system' },
  loadingData: { ro: 'Se încarcă datele...', en: 'Loading data...' },
  activeBusesLabel: { ro: 'Autobuze Active', en: 'Active Buses' },
  avgOccupancyLabel: { ro: 'Ocupare Medie', en: 'Average Occupancy' },
  totalRoutesLabel: { ro: 'Trasee Totale', en: 'Total Routes' },
  totalStationsLabel: { ro: 'Stații Totale', en: 'Total Stations' },
  avgOccupancyByRoute: { ro: 'Ocupare Medie pe Traseu', en: 'Average Occupancy by Route' },
  activeBusesRealtime: { ro: 'Autobuze Active în Timp Real', en: 'Real-time Active Buses' },
  occupancyDistribution: { ro: 'Distribuție Nivel Ocupare', en: 'Occupancy Distribution' },
  topStationsTraffic: { ro: 'Top Stații Tranzitate', en: 'Top Transit Stations' },
  liveBuses: { ro: 'Autobuze Live', en: 'Live Buses' },
  live: { ro: 'LIVE', en: 'LIVE' },
  speed: { ro: 'Viteză', en: 'Speed' },
  occupancy: { ro: 'Ocupare', en: 'Occupancy' },
  position: { ro: 'Poziție', en: 'Position' },
  occupancyAvgPercent: { ro: 'Ocupare Medie (%)', en: 'Average Occupancy (%)' },
  occupancyLow: { ro: 'Scăzută (<40%)', en: 'Low (<40%)' },
  occupancyMedium: { ro: 'Medie (40-70%)', en: 'Medium (40-70%)' },
  occupancyHigh: { ro: 'Ridicată (>70%)', en: 'High (>70%)' },
  passCount: { ro: 'Număr treceri', en: 'Pass count' },
  continueWithGoogle: { ro: 'Continuă cu Google', en: 'Continue with Google' },
  fleet: { ro: 'Flotă', en: 'Fleet' },
  users: { ro: 'Utilizatori', en: 'Users' },
  ticketsAndRevenue: { ro: 'Bilete & Venituri', en: 'Tickets & Revenue' },
  close: { ro: 'Închide', en: 'Close' },
  more: { ro: 'Mai mult', en: 'More' },
  tripHistory: { ro: 'Istoric călătorii', en: 'Trip History' },
  viewTutorial: { ro: 'Vezi tutorialul', en: 'View Tutorial' },
  viewTutorialDesc: { ro: 'Revedere ghidul de utilizare al aplicației', en: 'Review the app usage guide' },
  profile: { ro: 'Profilul meu', en: 'My Profile' },
  profileDesc: { ro: 'Statistici și activitate', en: 'Statistics and activity' },
  savedSuccessfully: { ro: 'Salvat cu succes!', en: 'Saved successfully!' },
  deletedSuccessfully: { ro: 'Șters cu succes!', en: 'Deleted successfully!' },
  addedToFavorites: { ro: 'Adăugat la favorite!', en: 'Added to favorites!' },
  confirmDelete: { ro: 'Ești sigur că vrei să ștergi?', en: 'Are you sure you want to delete?' }
}

const germanOverrides: Record<string, string> = {
  language: 'Sprache',
  romanian: 'Rumänisch',
  english: 'Englisch',
  german: 'Deutsch',
  map: 'Karte',
  favorites: 'Favoriten',
  tickets: 'Fahrkarten',
  date: 'Datum',
  routes: 'Routen',
  schedule: 'Fahrplan',
  planning: 'Planung',
  settings: 'Einstellungen',
  personalizeExperience: 'Passe deine Erfahrung an',
  appearance: 'Darstellung',
  darkMode: 'Dunkelmodus',
  darkModeDesc: 'Ändere das App-Design',
  disableDarkMode: 'Dunkelmodus deaktivieren',
  enableDarkMode: 'Dunkelmodus aktivieren',
  notifications: 'Benachrichtigungen',
  pushNotifications: 'Push-Benachrichtigungen',
  pushNotificationsDesc: 'Erhalte Bus-Benachrichtigungen',
  switchToLanguage: 'App auf {language} umstellen',
  switchLanguageAria: 'Sprache auf {language} umstellen',
  statistics: 'Statistiken',
  myStatistics: 'Meine Statistiken',
  usageStatisticsDesc: 'Nutzungsstatistiken anzeigen',
  account: 'Konto',
  authentication: 'Anmeldung',
  signInAccountDesc: 'Melde dich bei deinem Konto an',
  information: 'Informationen',
  version: 'Version',
  build: 'Build',
  aboutApp: 'Über die App',
  aboutAppDesc: 'Informationen und Entwickler',
  loading: 'Laden...',
  searching: 'Suche...',
  cancel: 'Abbrechen',
  save: 'Speichern',
  add: 'Hinzufügen',
  create: 'Erstellen',
  edit: 'Bearbeiten',
  delete: 'Löschen',
  actions: 'Aktionen',
  adminWelcome: 'Willkommen! Melde dich an, um fortzufahren',
  adminAccessRestricted: 'Der Zugriff ist auf autorisierte Administratoren beschränkt',
  adminBackToMap: 'Zurück zur Karte',
  adminWrongCredentials: 'Ungültiger Benutzername oder ungültiges Passwort',
  adminPanel: 'Admin-Panel',
  adminPanelSubtitle: 'Verwalte die öffentlichen Verkehrsrouten und Haltestellen in Sibiu',
  analytics: 'Analysen',
  logout: 'Abmelden',
  manageRoutes: 'Routen verwalten',
  addNewRoute: 'Neue Route hinzufügen',
  routeNumber: 'Routennummer',
  name: 'Name',
  color: 'Farbe',
  changeColor: 'Farbe ändern',
  editRouteTitle: 'Route bearbeiten',
  createRouteTitle: 'Neue Route hinzufügen',
  colorHex: 'Farbe (Hex)',
  changeColorTitle: 'Farbe ändern',
  newColor: 'Neue Farbe',
  confirmDeleteRoute: 'Möchtest du die Route {route} wirklich löschen?',
  routesLoadErrorWithMessage: 'Fehler beim Laden der Routen: {message}',
  routeDeleteError: 'Fehler beim Löschen der Route',
  routeSaveError: 'Fehler beim Speichern der Route',
  routeColorUpdateError: 'Fehler beim Aktualisieren der Farbe',
  manageStations: 'Haltestellen verwalten',
  addNewStation: 'Neue Haltestelle hinzufügen',
  stationName: 'Haltestellenname',
  latitude: 'Breitengrad',
  longitude: 'Längengrad',
  viewOnMap: 'Auf der Karte anzeigen',
  editStationTitle: 'Haltestelle bearbeiten',
  createStationTitle: 'Neue Haltestelle hinzufügen',
  stationExample: 'z. B. Hauptplatz',
  mapTip: 'Tipp: Klicke auf die Karte, um Koordinaten automatisch zu setzen',
  confirmDeleteStation: 'Möchtest du die Haltestelle "{name}" wirklich löschen?\n\nAchtung: Das kann Routen beeinflussen, die diese Haltestelle nutzen!',
  stationsLoadErrorWithMessage: 'Fehler beim Laden der Haltestellen: {message}',
  stationDeleteError: 'Fehler beim Löschen der Haltestelle',
  stationSaveError: 'Fehler beim Speichern der Haltestelle',
  analyticsDashboard: 'Analyse-Dashboard',
  analyticsSubtitle: 'Echtzeitstatistiken für das öffentliche Verkehrssystem',
  loadingData: 'Daten werden geladen...',
  activeBusesLabel: 'Aktive Busse',
  avgOccupancyLabel: 'Durchschnittliche Auslastung',
  totalRoutesLabel: 'Gesamte Routen',
  totalStationsLabel: 'Gesamte Haltestellen',
  avgOccupancyByRoute: 'Durchschnittliche Auslastung pro Route',
  activeBusesRealtime: 'Aktive Busse in Echtzeit',
  occupancyDistribution: 'Auslastungsverteilung',
  topStationsTraffic: 'Top-Haltestellen nach Verkehr',
  liveBuses: 'Live-Busse',
  speed: 'Geschwindigkeit',
  occupancy: 'Auslastung',
  position: 'Position',
  occupancyAvgPercent: 'Durchschnittliche Auslastung (%)',
  occupancyLow: 'Niedrig (<40%)',
  occupancyMedium: 'Mittel (40-70%)',
  occupancyHigh: 'Hoch (>70%)',
  passCount: 'Anzahl Durchfahrten',
  close: 'Schließen',
  more: 'Mehr',
  tripHistory: 'Reiseverlauf',
  viewTutorial: 'Tutorial ansehen',
  viewTutorialDesc: 'Nutzungsanleitung der App erneut ansehen',
  profile: 'Mein Profil',
  profileDesc: 'Statistiken und Aktivität',
  savedSuccessfully: 'Erfolgreich gespeichert!',
  deletedSuccessfully: 'Erfolgreich gelöscht!',
  addedToFavorites: 'Zu Favoriten hinzugefügt!',
  confirmDelete: 'Möchten Sie wirklich löschen?',
  ticketsAndRevenue: 'Fahrkarten & Einnahmen',
  fleet: 'Flotte',
  users: 'Benutzer'
}

const setLanguage = (language: Language) => {
  currentLanguage.value = language
  localStorage.setItem(STORAGE_KEY, language)
}

const toggleLanguage = () => {
  if (currentLanguage.value === 'ro') {
    setLanguage('en')
    return
  }
  if (currentLanguage.value === 'en') {
    setLanguage('de')
    return
  }
  setLanguage('ro')
}

const t = (key: string, fallback = key, params?: Record<string, string | number>) => {
  const entry = dictionary[key]
  if (!entry) {
    return fallback
  }
  let value = currentLanguage.value === 'de'
    ? germanOverrides[key] ?? entry.en
    : entry[currentLanguage.value]
  if (params) {
    Object.entries(params).forEach(([paramKey, paramValue]) => {
      value = value.replace(`{${paramKey}}`, String(paramValue))
    })
  }
  return value
}

export const useLanguage = () => ({
  currentLanguage,
  setLanguage,
  toggleLanguage,
  t
})

export type { Language }
