services:
  - type: web
    name: tursib-backend
    runtime: docker
    dockerfilePath: ./TursibBackend/Dockerfile
    dockerContext: ./TursibBackend
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
    healthCheckPath: /api/routes

  - type: web
    name: tursib-bus-simulator
    runtime: docker
    dockerfilePath: ./BusSimulator/Dockerfile
    dockerContext: ./BusSimulator
    plan: free
    envVars:
      - key: TURSIB_API_URL
        value: https://aplicatie-web-pentru-urmarirea-in-timp.onrender.com/api
      - key: FIREBASE_URL
        value: https://licenta-ulbs-default-rtdb.europe-west1.firebasedatabase.app/
