// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TursibBackend.Data;

#nullable disable

namespace TursibBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118093412_InitialWithPreciseCoordinates")]
    partial class InitialWithPreciseCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("TursibBackend.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentRouteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRouteId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentRouteId = 1,
                            InternalName = "Bus 101",
                            LicensePlate = "SB-01-ABC"
                        },
                        new
                        {
                            Id = 2,
                            CurrentRouteId = 2,
                            InternalName = "Bus 211",
                            LicensePlate = "SB-11-XYZ"
                        });
                });

            modelBuilder.Entity("TursibBackend.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cimitir - Hornbach",
                            RouteNumber = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kaufland Arhitecților - Continental",
                            RouteNumber = "11"
                        });
                });

            modelBuilder.Entity("TursibBackend.Models.RouteStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StationId");

                    b.ToTable("RouteStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Order = 1,
                            RouteId = 1,
                            StationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Order = 2,
                            RouteId = 1,
                            StationId = 2
                        },
                        new
                        {
                            Id = 3,
                            Order = 3,
                            RouteId = 1,
                            StationId = 3
                        },
                        new
                        {
                            Id = 4,
                            Order = 4,
                            RouteId = 1,
                            StationId = 4
                        },
                        new
                        {
                            Id = 5,
                            Order = 5,
                            RouteId = 1,
                            StationId = 5
                        },
                        new
                        {
                            Id = 6,
                            Order = 6,
                            RouteId = 1,
                            StationId = 6
                        },
                        new
                        {
                            Id = 7,
                            Order = 7,
                            RouteId = 1,
                            StationId = 7
                        },
                        new
                        {
                            Id = 8,
                            Order = 8,
                            RouteId = 1,
                            StationId = 8
                        },
                        new
                        {
                            Id = 9,
                            Order = 9,
                            RouteId = 1,
                            StationId = 9
                        },
                        new
                        {
                            Id = 10,
                            Order = 10,
                            RouteId = 1,
                            StationId = 10
                        },
                        new
                        {
                            Id = 11,
                            Order = 11,
                            RouteId = 1,
                            StationId = 11
                        },
                        new
                        {
                            Id = 12,
                            Order = 12,
                            RouteId = 1,
                            StationId = 12
                        },
                        new
                        {
                            Id = 13,
                            Order = 13,
                            RouteId = 1,
                            StationId = 13
                        },
                        new
                        {
                            Id = 14,
                            Order = 14,
                            RouteId = 1,
                            StationId = 14
                        },
                        new
                        {
                            Id = 15,
                            Order = 15,
                            RouteId = 1,
                            StationId = 15
                        },
                        new
                        {
                            Id = 16,
                            Order = 16,
                            RouteId = 1,
                            StationId = 16
                        },
                        new
                        {
                            Id = 17,
                            Order = 17,
                            RouteId = 1,
                            StationId = 17
                        },
                        new
                        {
                            Id = 18,
                            Order = 1,
                            RouteId = 2,
                            StationId = 20
                        },
                        new
                        {
                            Id = 19,
                            Order = 2,
                            RouteId = 2,
                            StationId = 21
                        },
                        new
                        {
                            Id = 20,
                            Order = 3,
                            RouteId = 2,
                            StationId = 22
                        },
                        new
                        {
                            Id = 21,
                            Order = 4,
                            RouteId = 2,
                            StationId = 4
                        },
                        new
                        {
                            Id = 22,
                            Order = 5,
                            RouteId = 2,
                            StationId = 23
                        },
                        new
                        {
                            Id = 23,
                            Order = 6,
                            RouteId = 2,
                            StationId = 24
                        },
                        new
                        {
                            Id = 24,
                            Order = 7,
                            RouteId = 2,
                            StationId = 25
                        },
                        new
                        {
                            Id = 25,
                            Order = 8,
                            RouteId = 2,
                            StationId = 26
                        },
                        new
                        {
                            Id = 26,
                            Order = 9,
                            RouteId = 2,
                            StationId = 27
                        },
                        new
                        {
                            Id = 27,
                            Order = 10,
                            RouteId = 2,
                            StationId = 8
                        },
                        new
                        {
                            Id = 28,
                            Order = 11,
                            RouteId = 2,
                            StationId = 9
                        },
                        new
                        {
                            Id = 29,
                            Order = 12,
                            RouteId = 2,
                            StationId = 28
                        },
                        new
                        {
                            Id = 30,
                            Order = 13,
                            RouteId = 2,
                            StationId = 29
                        });
                });

            modelBuilder.Entity("TursibBackend.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 45.767937199999999,
                            Longitude = 24.138513,
                            Name = "Cimitir"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 45.770434199999997,
                            Longitude = 24.138480999999999,
                            Name = "Calea Dumbrăvii (Cimitir)"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 45.772008800000002,
                            Longitude = 24.140490700000001,
                            Name = "Str. Siretului"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 45.774553900000001,
                            Longitude = 24.1485366,
                            Name = "Calea Cisnădiei"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 45.777395499999997,
                            Longitude = 24.157934999999998,
                            Name = "Str. Rahovei (Piața Rahova)"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 45.779129599999997,
                            Longitude = 24.155641800000001,
                            Name = "B-dul M. Viteazu"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 45.781767199999997,
                            Longitude = 24.149777199999999,
                            Name = "Calea Dumbrăvii (Viteazu)"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 45.790972400000001,
                            Longitude = 24.148515199999999,
                            Name = "Piața Unirii"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 45.792625899999997,
                            Longitude = 24.1408296,
                            Name = "Str. A. Șaguna"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 45.792625899999997,
                            Longitude = 24.1408296,
                            Name = "Șos. Alba Iulia"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 45.7961989,
                            Longitude = 24.139075699999999,
                            Name = "Str. Malului"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 45.798989400000004,
                            Longitude = 24.144453899999998,
                            Name = "Piața Cibin"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 45.799472999999999,
                            Longitude = 24.1442871,
                            Name = "Str. Cibinului"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 45.808641700000003,
                            Longitude = 24.1495909,
                            Name = "Str. Rusciorului"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 45.807449599999998,
                            Longitude = 24.1458732,
                            Name = "Str. Lungă"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 45.811254400000003,
                            Longitude = 24.148464000000001,
                            Name = "Calea Șurii Mari (Halta Sibiu)"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 45.821075399999998,
                            Longitude = 24.1491845,
                            Name = "Hornbach"
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 45.770613599999997,
                            Longitude = 24.146665599999999,
                            Name = "Kaufland Arhitecților"
                        },
                        new
                        {
                            Id = 21,
                            Latitude = 45.772673699999999,
                            Longitude = 24.1481128,
                            Name = "C. Cisnădiei - Primăverii"
                        },
                        new
                        {
                            Id = 22,
                            Latitude = 45.754687599999997,
                            Longitude = 24.138710199999998,
                            Name = "Cartierul Primăverii"
                        },
                        new
                        {
                            Id = 23,
                            Latitude = 45.777395499999997,
                            Longitude = 24.157934999999998,
                            Name = "Str. Rahova"
                        },
                        new
                        {
                            Id = 24,
                            Latitude = 45.778119699999998,
                            Longitude = 24.149690799999998,
                            Name = "B-dul M. Viteazu (Iorga)"
                        },
                        new
                        {
                            Id = 25,
                            Latitude = 45.780909999999999,
                            Longitude = 24.158085,
                            Name = "Str. N. Iorga / Cedonia"
                        },
                        new
                        {
                            Id = 26,
                            Latitude = 45.782547200000003,
                            Longitude = 24.162478700000001,
                            Name = "Str. Luptei"
                        },
                        new
                        {
                            Id = 27,
                            Latitude = 45.788394400000001,
                            Longitude = 24.151538299999999,
                            Name = "B-dul V. Milea"
                        },
                        new
                        {
                            Id = 28,
                            Latitude = 45.796409099999998,
                            Longitude = 24.078269800000001,
                            Name = "Str. Salzburg"
                        },
                        new
                        {
                            Id = 29,
                            Latitude = 45.797894700000001,
                            Longitude = 24.077089300000001,
                            Name = "S.C. Continental"
                        });
                });

            modelBuilder.Entity("TursibBackend.Models.Bus", b =>
                {
                    b.HasOne("TursibBackend.Models.Route", "CurrentRoute")
                        .WithMany()
                        .HasForeignKey("CurrentRouteId");

                    b.Navigation("CurrentRoute");
                });

            modelBuilder.Entity("TursibBackend.Models.RouteStation", b =>
                {
                    b.HasOne("TursibBackend.Models.Route", "Route")
                        .WithMany("RouteStations")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TursibBackend.Models.Station", "Station")
                        .WithMany("RouteStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TursibBackend.Models.Route", b =>
                {
                    b.Navigation("RouteStations");
                });

            modelBuilder.Entity("TursibBackend.Models.Station", b =>
                {
                    b.Navigation("RouteStations");
                });
#pragma warning restore 612, 618
        }
    }
}
